/**
 * WBUHS B.Sc. Nursing 7th Semester - Exact 80 Questions Bank
 * Final Official Answer Set for 2-Mark High-Yield Revision
 */
const QUESTIONS = [
  {
    "id": 1,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Antenatal Care",
    "question": "Define antenatal care.",
    "answer": "Antenatal care is the systematic care provided to a pregnant woman from early pregnancy until the onset of labour.\n\nObjectives include:\n1. To assess and monitor maternal health.\n2. To assess fetal growth and wellbeing.\n3. To detect and manage complications at an early stage.\n4. To prepare the mother physically and psychologically for labour and parenthood.",
    "type": "Definition",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "anc",
      "antenatal care",
      "maternal",
      "fetal growth",
      "pregnancy"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Define antenatal care.",
    "a": "Antenatal care is the systematic care provided to a pregnant woman from early pregnancy until the onset of labour.\n\nObjectives include:\n1. To assess and monitor maternal health.\n2. To assess fetal growth and wellbeing.\n3. To detect and manage complications at an early stage.\n4. To prepare the mother physically and psychologically for labour and parenthood.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 2,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Antenatal Care",
    "question": "Mention any four objectives of antenatal care.",
    "answer": "1. To assess and monitor maternal health.\n2. To assess fetal growth and wellbeing.\n3. To detect and manage complications at an early stage.\n4. To prepare the mother physically and psychologically for labour and parenthood.",
    "type": "Mention",
    "important": true,
    "priority": "important",
    "keywords": [
      "anc objectives",
      "antenatal objectives",
      "antenatal goals",
      "maternal health"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Mention any four objectives of antenatal care.",
    "a": "1. To assess and monitor maternal health.\n2. To assess fetal growth and wellbeing.\n3. To detect and manage complications at an early stage.\n4. To prepare the mother physically and psychologically for labour and parenthood.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 3,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "True Labour Signs",
    "question": "State two signs of true labour.",
    "answer": "1. Regular uterine contractions that progressively increase in frequency, duration and intensity.\n2. Progressive cervical changes, including cervical effacement and dilatation.",
    "type": "Signs",
    "important": true,
    "priority": "important",
    "keywords": [
      "true labour",
      "contractions",
      "effacement",
      "cervical dilatation"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "State two signs of true labour.",
    "a": "1. Regular uterine contractions that progressively increase in frequency, duration and intensity.\n2. Progressive cervical changes, including cervical effacement and dilatation.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 4,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "True vs False Labour",
    "question": "Differentiate between true labour and false labour.",
    "answer": "True labour:\n1. Contractions become regular and progressively stronger.\n2. Cervical effacement and dilatation occur progressively.\n3. Contractions generally continue despite rest or change of activity.\n\nFalse labour:\n1. Contractions are irregular and usually do not progressively increase.\n2. There is no progressive cervical dilatation.\n3. Contractions may decrease with rest or change of activity.",
    "type": "Differentiate",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "true labour",
      "false labour",
      "braxton hicks",
      "cervical changes",
      "contractions"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Differentiate between true labour and false labour.",
    "a": "True labour:\n1. Contractions become regular and progressively stronger.\n2. Cervical effacement and dilatation occur progressively.\n3. Contractions generally continue despite rest or change of activity.\n\nFalse labour:\n1. Contractions are irregular and usually do not progressively increase.\n2. There is no progressive cervical dilatation.\n3. Contractions may decrease with rest or change of activity.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 5,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "First Stage of Labour",
    "question": "Write two immediate measures in the first stage of labour.",
    "answer": "1. Monitor maternal vital signs, uterine contractions and fetal heart rate regularly.\n2. Provide emotional support, comfort measures, hydration and encourage appropriate breathing and relaxation techniques.",
    "type": "Immediate Management",
    "important": false,
    "priority": "important",
    "keywords": [
      "first stage",
      "labour care",
      "fhr",
      "fetal heart rate",
      "vital signs",
      "hydration"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Write two immediate measures in the first stage of labour.",
    "a": "1. Monitor maternal vital signs, uterine contractions and fetal heart rate regularly.\n2. Provide emotional support, comfort measures, hydration and encourage appropriate breathing and relaxation techniques.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 6,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Postpartum Haemorrhage (PPH)",
    "question": "Define postpartum haemorrhage (PPH).",
    "answer": "Postpartum haemorrhage is excessive bleeding following childbirth. Primary PPH occurs within the first 24 hours after birth and is clinically important because severe blood loss can cause maternal shock and organ complications.",
    "type": "Definition",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "pph",
      "postpartum haemorrhage",
      "postpartum hemorrhage",
      "excessive bleeding",
      "primary pph",
      "shock"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Define postpartum haemorrhage (PPH).",
    "a": "Postpartum haemorrhage is excessive bleeding following childbirth. Primary PPH occurs within the first 24 hours after birth and is clinically important because severe blood loss can cause maternal shock and organ complications.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 7,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Causes of PPH",
    "question": "List four causes of PPH.",
    "answer": "The four major causes are:\n1. Uterine atony.\n2. Retained placental tissue.\n3. Genital tract trauma such as tears.\n4. Coagulation disorders.",
    "type": "Causes",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "pph causes",
      "uterine atony",
      "retained placenta",
      "trauma",
      "coagulation",
      "4 ts"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "List four causes of PPH.",
    "a": "The four major causes are:\n1. Uterine atony.\n2. Retained placental tissue.\n3. Genital tract trauma such as tears.\n4. Coagulation disorders.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 8,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Complications of PPH",
    "question": "State two complications of PPH.",
    "answer": "1. Hypovolaemic shock due to severe blood loss.\n2. Severe anaemia, which may lead to weakness, organ dysfunction and other complications.",
    "type": "Complications",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "pph complications",
      "hypovolaemic shock",
      "hypovolemic shock",
      "severe anaemia",
      "organ dysfunction"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "State two complications of PPH.",
    "a": "1. Hypovolaemic shock due to severe blood loss.\n2. Severe anaemia, which may lead to weakness, organ dysfunction and other complications.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 9,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Immediate Management of PPH",
    "question": "Mention two immediate nursing measures for PPH.",
    "answer": "1. Call for assistance, assess the mother, monitor vital signs and estimate blood loss.\n2. Maintain intravenous access and administer prescribed uterotonics, fluids and blood products as indicated.",
    "type": "Immediate Management",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "pph nursing measures",
      "pph management",
      "iv access",
      "uterotonics",
      "vital signs"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Mention two immediate nursing measures for PPH.",
    "a": "1. Call for assistance, assess the mother, monitor vital signs and estimate blood loss.\n2. Maintain intravenous access and administer prescribed uterotonics, fluids and blood products as indicated.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 10,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Uterotonics in PPH",
    "question": "Name two uterotonics used in management of PPH.",
    "answer": "1. Oxytocin.\n2. Misoprostol.",
    "type": "Name",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "uterotonics",
      "oxytocin",
      "misoprostol",
      "pph medicines",
      "uterotonic drugs"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Name two uterotonics used in management of PPH.",
    "a": "1. Oxytocin.\n2. Misoprostol.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 11,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Pre-eclampsia",
    "question": "Define pre-eclampsia.",
    "answer": "Pre-eclampsia is a pregnancy-specific hypertensive disorder, usually occurring after 20 weeks of pregnancy, characterized by new-onset hypertension associated with proteinuria and/or other maternal organ or placental dysfunction.",
    "type": "Definition",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "pre-eclampsia",
      "preeclampsia",
      "hypertension in pregnancy",
      "proteinuria",
      "20 weeks"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Define pre-eclampsia.",
    "a": "Pre-eclampsia is a pregnancy-specific hypertensive disorder, usually occurring after 20 weeks of pregnancy, characterized by new-onset hypertension associated with proteinuria and/or other maternal organ or placental dysfunction.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 12,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Signs of Severe Pre-eclampsia",
    "question": "Mention four signs and symptoms of severe pre-eclampsia.",
    "answer": "1. Severe or persistent headache.\n2. Visual disturbances such as blurred vision or flashing lights.\n3. Severe epigastric or right upper abdominal pain.\n4. Severe hypertension.\n\nOther severe features may include reduced urine output, pulmonary oedema and abnormal laboratory findings.",
    "type": "Signs and Symptoms",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "severe pre-eclampsia",
      "headache",
      "visual disturbance",
      "epigastric pain",
      "severe hypertension"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Mention four signs and symptoms of severe pre-eclampsia.",
    "a": "1. Severe or persistent headache.\n2. Visual disturbances such as blurred vision or flashing lights.\n3. Severe epigastric or right upper abdominal pain.\n4. Severe hypertension.\n\nOther severe features may include reduced urine output, pulmonary oedema and abnormal laboratory findings.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 13,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Complications of Eclampsia",
    "question": "State two complications of eclampsia.",
    "answer": "1. Cerebral complications such as stroke or brain injury.\n2. Fetal hypoxia or fetal distress due to maternal seizures and impaired placental oxygenation.",
    "type": "Complications",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "eclampsia",
      "eclampsia complications",
      "stroke",
      "brain injury",
      "fetal hypoxia",
      "seizures"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "State two complications of eclampsia.",
    "a": "1. Cerebral complications such as stroke or brain injury.\n2. Fetal hypoxia or fetal distress due to maternal seizures and impaired placental oxygenation.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 14,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Magnesium Sulphate Uses",
    "question": "Name two uses of magnesium sulphate in obstetric care.",
    "answer": "1. To prevent seizures in women with severe pre-eclampsia when indicated.\n2. To treat and prevent recurrent seizures in eclampsia.",
    "type": "Uses",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "magnesium sulphate",
      "mgso4",
      "seizure prevention",
      "eclampsia treatment",
      "anticonvulsant"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Name two uses of magnesium sulphate in obstetric care.",
    "a": "1. To prevent seizures in women with severe pre-eclampsia when indicated.\n2. To treat and prevent recurrent seizures in eclampsia.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 15,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Magnesium Sulphate Therapy",
    "question": "Mention two important nursing responsibilities during magnesium sulphate therapy.",
    "answer": "1. Monitor respiratory rate, urine output and deep tendon reflexes for signs of magnesium toxicity.\n2. Keep the prescribed calcium gluconate antidote available and report signs of toxicity immediately.",
    "type": "Nursing Responsibilities",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "magnesium sulphate",
      "mgso4 toxicity",
      "calcium gluconate",
      "patellar reflex",
      "knee jerk",
      "respiratory rate"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Mention two important nursing responsibilities during magnesium sulphate therapy.",
    "a": "1. Monitor respiratory rate, urine output and deep tendon reflexes for signs of magnesium toxicity.\n2. Keep the prescribed calcium gluconate antidote available and report signs of toxicity immediately.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 16,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Gestational Diabetes Mellitus (GDM)",
    "question": "What is gestational diabetes mellitus?",
    "answer": "Gestational diabetes mellitus (GDM) is diabetes first diagnosed during pregnancy.\n\nImportant points:\n1. It causes abnormal elevation of blood glucose during pregnancy.\n2. It may increase maternal and fetal/newborn complications.\n3. Proper glucose control and regular antenatal monitoring are important.",
    "type": "Definition",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "gdm",
      "gestational diabetes mellitus",
      "hyperglycemia",
      "diabetes in pregnancy"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "What is gestational diabetes mellitus?",
    "a": "Gestational diabetes mellitus (GDM) is diabetes first diagnosed during pregnancy.\n\nImportant points:\n1. It causes abnormal elevation of blood glucose during pregnancy.\n2. It may increase maternal and fetal/newborn complications.\n3. Proper glucose control and regular antenatal monitoring are important.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 17,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Complications of GDM",
    "question": "List four complications of GDM.",
    "answer": "1. Maternal hypertensive disorders, including pre-eclampsia.\n2. Fetal macrosomia.\n3. Increased risk of difficult labour and birth trauma.\n4. Neonatal hypoglycaemia.",
    "type": "Complications",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "gdm complications",
      "macrosomia",
      "neonatal hypoglycaemia",
      "birth trauma",
      "preeclampsia"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "List four complications of GDM.",
    "a": "1. Maternal hypertensive disorders, including pre-eclampsia.\n2. Fetal macrosomia.\n3. Increased risk of difficult labour and birth trauma.\n4. Neonatal hypoglycaemia.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 18,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Maternal Complications of GDM",
    "question": "Mention two maternal complications of GDM.",
    "answer": "1. Hypertensive disorders, including pre-eclampsia.\n2. Increased risk of operative delivery, particularly when fetal overgrowth complicates labour.",
    "type": "Complications",
    "important": true,
    "priority": "important",
    "keywords": [
      "gdm maternal complications",
      "pre-eclampsia",
      "operative delivery",
      "cesarean"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Mention two maternal complications of GDM.",
    "a": "1. Hypertensive disorders, including pre-eclampsia.\n2. Increased risk of operative delivery, particularly when fetal overgrowth complicates labour.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 19,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Fetal Complications of GDM",
    "question": "Mention two fetal/newborn complications of GDM.",
    "answer": "1. Macrosomia or excessive fetal growth.\n2. Neonatal hypoglycaemia.",
    "type": "Complications",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "gdm fetal complications",
      "macrosomia",
      "neonatal hypoglycaemia",
      "fetal overgrowth"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Mention two fetal/newborn complications of GDM.",
    "a": "1. Macrosomia or excessive fetal growth.\n2. Neonatal hypoglycaemia.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 20,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Nursing Care in GDM",
    "question": "State two important aspects of nursing care for a mother with GDM.",
    "answer": "1. Monitor blood glucose and support the prescribed nutritional plan and treatment.\n2. Provide education regarding medication or insulin when prescribed, fetal monitoring, warning signs and follow-up.",
    "type": "Nursing Care",
    "important": false,
    "priority": "important",
    "keywords": [
      "gdm nursing care",
      "blood glucose",
      "insulin",
      "nutritional plan",
      "fetal monitoring"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "State two important aspects of nursing care for a mother with GDM.",
    "a": "1. Monitor blood glucose and support the prescribed nutritional plan and treatment.\n2. Provide education regarding medication or insulin when prescribed, fetal monitoring, warning signs and follow-up.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 21,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Preterm Newborn",
    "question": "Define preterm newborn.",
    "answer": "A preterm newborn is a baby born before 37 completed weeks of gestation, irrespective of birth weight.",
    "type": "Definition",
    "important": true,
    "priority": "important",
    "keywords": [
      "preterm newborn",
      "preterm baby",
      "before 37 weeks",
      "gestation"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Define preterm newborn.",
    "a": "A preterm newborn is a baby born before 37 completed weeks of gestation, irrespective of birth weight.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 22,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Preterm Baby Characteristics",
    "question": "Mention four characteristics of a preterm baby.",
    "answer": "1. Low birth weight.\n2. Thin, delicate or translucent skin.\n3. Reduced subcutaneous fat.\n4. Immature thermoregulation with increased risk of hypothermia.\n\nOther features may include reduced muscle tone and immature reflexes.",
    "type": "Characteristics",
    "important": true,
    "priority": "important",
    "keywords": [
      "preterm characteristics",
      "low birth weight",
      "thin skin",
      "hypothermia",
      "subcutaneous fat"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Mention four characteristics of a preterm baby.",
    "a": "1. Low birth weight.\n2. Thin, delicate or translucent skin.\n3. Reduced subcutaneous fat.\n4. Immature thermoregulation with increased risk of hypothermia.\n\nOther features may include reduced muscle tone and immature reflexes.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 23,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Complications of Prematurity",
    "question": "List four complications of prematurity.",
    "answer": "1. Respiratory distress.\n2. Hypothermia.\n3. Feeding difficulties.\n4. Increased risk of infection.",
    "type": "Complications",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "prematurity complications",
      "respiratory distress",
      "hypothermia",
      "feeding difficulties",
      "infection"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "List four complications of prematurity.",
    "a": "1. Respiratory distress.\n2. Hypothermia.\n3. Feeding difficulties.\n4. Increased risk of infection.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 24,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Principles of Preterm Care",
    "question": "State two important principles of care of a preterm newborn.",
    "answer": "1. Maintain body temperature through appropriate thermal care and skin-to-skin or Kangaroo Mother Care when suitable.\n2. Provide adequate feeding and monitor breathing, infection, glucose and other complications according to the baby's condition.",
    "type": "Nursing Care",
    "important": false,
    "priority": "important",
    "keywords": [
      "preterm care principles",
      "thermal care",
      "kmc",
      "kangaroo mother care",
      "feeding",
      "infection"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "State two important principles of care of a preterm newborn.",
    "a": "1. Maintain body temperature through appropriate thermal care and skin-to-skin or Kangaroo Mother Care when suitable.\n2. Provide adequate feeding and monitor breathing, infection, glucose and other complications according to the baby's condition.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 25,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Skin-to-Skin Contact",
    "question": "What is skin-to-skin contact?",
    "answer": "Skin-to-skin contact is the practice of placing the newborn directly on the mother's bare chest, usually covered with a warm cloth.\n\nBenefits:\n1. Maintains the baby's body temperature.\n2. Promotes breastfeeding and bonding.\n3. Helps stabilize the newborn.",
    "type": "Definition",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "skin-to-skin",
      "kmc",
      "kangaroo mother care",
      "body temperature",
      "bonding",
      "breastfeeding"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "What is skin-to-skin contact?",
    "a": "Skin-to-skin contact is the practice of placing the newborn directly on the mother's bare chest, usually covered with a warm cloth.\n\nBenefits:\n1. Maintains the baby's body temperature.\n2. Promotes breastfeeding and bonding.\n3. Helps stabilize the newborn.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 26,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Low Birth Weight",
    "question": "Define low birth weight.",
    "answer": "Low birth weight (LBW) is a birth weight of less than 2,500 grams, irrespective of the gestational age of the newborn.",
    "type": "Definition",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "lbw",
      "low birth weight",
      "less than 2500 grams",
      "birth weight"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Define low birth weight.",
    "a": "Low birth weight (LBW) is a birth weight of less than 2,500 grams, irrespective of the gestational age of the newborn.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 27,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Causes of Low Birth Weight",
    "question": "State four causes of low birth weight.",
    "answer": "1. Prematurity.\n2. Intrauterine growth restriction.\n3. Multiple pregnancy.\n4. Maternal factors such as poor nutrition, hypertension or other pregnancy complications.",
    "type": "Causes",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "lbw causes",
      "causes of low birth weight",
      "prematurity",
      "iugr",
      "malnutrition",
      "hypertension"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "State four causes of low birth weight.",
    "a": "1. Prematurity.\n2. Intrauterine growth restriction.\n3. Multiple pregnancy.\n4. Maternal factors such as poor nutrition, hypertension or other pregnancy complications.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 28,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Intrauterine Growth Restriction (IUGR)",
    "question": "Define intrauterine growth restriction.",
    "answer": "Intrauterine growth restriction (IUGR) is a condition in which the fetus fails to achieve its expected growth potential because of a pathological process during pregnancy.\n\nImportant point:\nAn IUGR baby may be term or preterm and is usually smaller than expected for gestational age.",
    "type": "Definition",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "iugr",
      "intrauterine growth restriction",
      "fetal growth",
      "growth potential",
      "small for gestational age"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Define intrauterine growth restriction.",
    "a": "Intrauterine growth restriction (IUGR) is a condition in which the fetus fails to achieve its expected growth potential because of a pathological process during pregnancy.\n\nImportant point:\nAn IUGR baby may be term or preterm and is usually smaller than expected for gestational age.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 29,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Complications of IUGR",
    "question": "Mention two complications of IUGR.",
    "answer": "1. Fetal hypoxia and fetal distress.\n2. Neonatal complications such as hypoglycaemia and hypothermia.",
    "type": "Complications",
    "important": true,
    "priority": "important",
    "keywords": [
      "iugr complications",
      "fetal hypoxia",
      "fetal distress",
      "hypoglycaemia",
      "hypothermia"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Mention two complications of IUGR.",
    "a": "1. Fetal hypoxia and fetal distress.\n2. Neonatal complications such as hypoglycaemia and hypothermia.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 30,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Preterm vs IUGR",
    "question": "Differentiate between preterm baby and IUGR baby.",
    "answer": "Preterm baby:\n1. Born before 37 completed weeks.\n2. Main problem is immaturity of organs and body systems.\n3. May have normal size for its gestational age.\n\nIUGR baby:\n1. Has restricted growth below expected potential.\n2. Main problem is impaired fetal growth.\n3. Usually has low weight or size for gestational age.",
    "type": "Differentiate",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "preterm vs iugr",
      "preterm baby",
      "iugr baby",
      "difference preterm iugr"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Differentiate between preterm baby and IUGR baby.",
    "a": "Preterm baby:\n1. Born before 37 completed weeks.\n2. Main problem is immaturity of organs and body systems.\n3. May have normal size for its gestational age.\n\nIUGR baby:\n1. Has restricted growth below expected potential.\n2. Main problem is impaired fetal growth.\n3. Usually has low weight or size for gestational age.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 31,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Puerperium",
    "question": "Define puerperium.",
    "answer": "Puerperium is the period following childbirth during which the reproductive organs and other maternal changes gradually return toward the non-pregnant state. It is traditionally considered to be approximately six weeks.",
    "type": "Definition",
    "important": true,
    "priority": "important",
    "keywords": [
      "puerperium",
      "postpartum period",
      "involution",
      "six weeks"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Define puerperium.",
    "a": "Puerperium is the period following childbirth during which the reproductive organs and other maternal changes gradually return toward the non-pregnant state. It is traditionally considered to be approximately six weeks.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 32,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Physiological Changes in Puerperium",
    "question": "Mention four physiological changes during puerperium.",
    "answer": "1. Uterine involution occurs.\n2. Lochia is discharged and gradually changes in amount and colour.\n3. Cervix and genital tract gradually return toward the non-pregnant state.\n4. Breast changes occur with the establishment of lactation.",
    "type": "Physiological Changes",
    "important": true,
    "priority": "important",
    "keywords": [
      "puerperium changes",
      "uterine involution",
      "lochia",
      "lactation"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Mention four physiological changes during puerperium.",
    "a": "1. Uterine involution occurs.\n2. Lochia is discharged and gradually changes in amount and colour.\n3. Cervix and genital tract gradually return toward the non-pregnant state.\n4. Breast changes occur with the establishment of lactation.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 33,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Puerperal Sepsis",
    "question": "What is puerperal sepsis?",
    "answer": "Puerperal sepsis is infection of the genital tract or surrounding tissues occurring during labour or after childbirth and associated with maternal systemic illness and/or local signs of infection.",
    "type": "Definition",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "puerperal sepsis",
      "postpartum infection",
      "genital tract infection",
      "childbed fever"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "What is puerperal sepsis?",
    "a": "Puerperal sepsis is infection of the genital tract or surrounding tissues occurring during labour or after childbirth and associated with maternal systemic illness and/or local signs of infection.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 34,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Signs of Puerperal Sepsis",
    "question": "List four signs of puerperal sepsis.",
    "answer": "1. Fever.\n2. Foul-smelling lochia.\n3. Lower abdominal or uterine tenderness.\n4. Tachycardia or other signs of systemic infection.",
    "type": "Signs",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "puerperal sepsis signs",
      "fever",
      "foul lochia",
      "uterine tenderness",
      "tachycardia"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "List four signs of puerperal sepsis.",
    "a": "1. Fever.\n2. Foul-smelling lochia.\n3. Lower abdominal or uterine tenderness.\n4. Tachycardia or other signs of systemic infection.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 35,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Prevention of Puerperal Infection",
    "question": "State two measures for prevention of puerperal infection.",
    "answer": "1. Maintain strict hand hygiene and aseptic technique during labour and delivery.\n2. Avoid unnecessary vaginal examinations and identify and treat maternal infections promptly.",
    "type": "Prevention",
    "important": false,
    "priority": "important",
    "keywords": [
      "puerperal infection prevention",
      "hand hygiene",
      "aseptic technique",
      "vaginal examinations"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "State two measures for prevention of puerperal infection.",
    "a": "1. Maintain strict hand hygiene and aseptic technique during labour and delivery.\n2. Avoid unnecessary vaginal examinations and identify and treat maternal infections promptly.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 36,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Induction of Labour",
    "question": "Define induction of labour.",
    "answer": "Induction of labour is the deliberate initiation of uterine contractions before the spontaneous onset of labour with the aim of achieving vaginal birth.",
    "type": "Definition",
    "important": true,
    "priority": "important",
    "keywords": [
      "induction of labour",
      "iol",
      "initiation of contractions",
      "vaginal birth"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Define induction of labour.",
    "a": "Induction of labour is the deliberate initiation of uterine contractions before the spontaneous onset of labour with the aim of achieving vaginal birth.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 37,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Indications for Induction of Labour",
    "question": "List four indications for induction of labour.",
    "answer": "1. Post-term pregnancy when delivery is indicated.\n2. Prelabour rupture of membranes when delivery is appropriate.\n3. Certain maternal hypertensive disorders.\n4. Selected fetal conditions in which continuation of pregnancy is not advisable.",
    "type": "Indications",
    "important": true,
    "priority": "important",
    "keywords": [
      "induction indications",
      "post-term",
      "prom",
      "hypertensive disorders",
      "fetal conditions"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "List four indications for induction of labour.",
    "a": "1. Post-term pregnancy when delivery is indicated.\n2. Prelabour rupture of membranes when delivery is appropriate.\n3. Certain maternal hypertensive disorders.\n4. Selected fetal conditions in which continuation of pregnancy is not advisable.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 38,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Methods of Induction of Labour",
    "question": "Name two methods of induction of labour.",
    "answer": "1. Cervical ripening with prostaglandins.\n2. Oxytocin infusion to stimulate uterine contractions.",
    "type": "Methods",
    "important": true,
    "priority": "important",
    "keywords": [
      "induction methods",
      "prostaglandins",
      "cervical ripening",
      "oxytocin infusion"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Name two methods of induction of labour.",
    "a": "1. Cervical ripening with prostaglandins.\n2. Oxytocin infusion to stimulate uterine contractions.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 39,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Complications of Induction of Labour",
    "question": "State two complications of induction of labour.",
    "answer": "1. Uterine tachysystole or excessive uterine contractions.\n2. Fetal heart rate abnormalities or fetal distress.",
    "type": "Complications",
    "important": true,
    "priority": "important",
    "keywords": [
      "induction complications",
      "uterine tachysystole",
      "fetal heart rate",
      "fetal distress"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "State two complications of induction of labour.",
    "a": "1. Uterine tachysystole or excessive uterine contractions.\n2. Fetal heart rate abnormalities or fetal distress.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 40,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Nursing Responsibilities in Induction",
    "question": "Mention two nursing responsibilities during induction of labour.",
    "answer": "1. Monitor fetal heart rate and uterine contractions regularly.\n2. Administer prescribed induction agents safely and observe for uterine hyperstimulation, fetal distress and other complications.",
    "type": "Nursing Responsibilities",
    "important": false,
    "priority": "important",
    "keywords": [
      "induction nursing care",
      "fetal heart rate",
      "uterine hyperstimulation",
      "contractions"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Mention two nursing responsibilities during induction of labour.",
    "a": "1. Monitor fetal heart rate and uterine contractions regularly.\n2. Administer prescribed induction agents safely and observe for uterine hyperstimulation, fetal distress and other complications.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 41,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Partograph",
    "question": "What is a partograph?",
    "answer": "A partograph is a graphical tool used during labour to record maternal and fetal observations and assess the progress of labour.\n\nPurpose:\n1. Helps monitor progress of labour.\n2. Helps identify abnormal labour early.\n3. Facilitates timely intervention or referral.",
    "type": "Definition",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "partograph",
      "partogram",
      "graphical tool",
      "progress of labour",
      "abnormal labour"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "What is a partograph?",
    "a": "A partograph is a graphical tool used during labour to record maternal and fetal observations and assess the progress of labour.\n\nPurpose:\n1. Helps monitor progress of labour.\n2. Helps identify abnormal labour early.\n3. Facilitates timely intervention or referral.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 42,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Partograph Parameters",
    "question": "Mention four parameters recorded on a partograph.",
    "answer": "1. Fetal heart rate.\n2. Cervical dilatation.\n3. Uterine contractions.\n4. Maternal pulse.\n\nOther observations may include liquor, moulding, blood pressure and temperature depending on the format used.",
    "type": "Parameters",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "partograph parameters",
      "fetal heart rate",
      "cervical dilatation",
      "uterine contractions",
      "maternal pulse"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Mention four parameters recorded on a partograph.",
    "a": "1. Fetal heart rate.\n2. Cervical dilatation.\n3. Uterine contractions.\n4. Maternal pulse.\n\nOther observations may include liquor, moulding, blood pressure and temperature depending on the format used.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 43,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Purposes of Partograph",
    "question": "State two purposes of a partograph.",
    "answer": "1. To monitor the progress of labour.\n2. To identify abnormal labour early and help initiate timely management or referral.",
    "type": "Uses",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "partograph purposes",
      "monitor progress",
      "abnormal labour",
      "timely management",
      "referral"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "State two purposes of a partograph.",
    "a": "1. To monitor the progress of labour.\n2. To identify abnormal labour early and help initiate timely management or referral.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 44,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Cord Prolapse",
    "question": "Define cord prolapse.",
    "answer": "Cord prolapse is the descent of the umbilical cord through the cervix alongside or past the presenting part after rupture of the membranes.\n\nImportance:\nIt can compress the cord and reduce fetal oxygenation, making it an obstetric emergency.",
    "type": "Definition",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "cord prolapse",
      "umbilical cord",
      "obstetric emergency",
      "fetal oxygenation",
      "compression"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Define cord prolapse.",
    "a": "Cord prolapse is the descent of the umbilical cord through the cervix alongside or past the presenting part after rupture of the membranes.\n\nImportance:\nIt can compress the cord and reduce fetal oxygenation, making it an obstetric emergency.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 45,
    "subject": "Midwifery & Obstetrical Nursing",
    "topic": "Immediate Management of Cord Prolapse",
    "question": "Mention two immediate measures for cord prolapse.",
    "answer": "1. Relieve pressure on the cord by elevating the presenting part and placing the mother in an appropriate position.\n2. Call for urgent obstetric assistance and prepare for expedited delivery as indicated.",
    "type": "Immediate Management",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "cord prolapse measures",
      "relieve pressure",
      "elevating presenting part",
      "expedited delivery"
    ],
    "cat": "Midwifery & Obstetrical Nursing",
    "q": "Mention two immediate measures for cord prolapse.",
    "a": "1. Relieve pressure on the cord by elevating the presenting part and placing the mother in an appropriate position.\n2. Call for urgent obstetric assistance and prepare for expedited delivery as indicated.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 46,
    "subject": "Newborn Care",
    "topic": "Healthy Newborn",
    "question": "Define healthy newborn.",
    "answer": "A healthy newborn is a baby born at or near term who establishes effective breathing, has stable vital functions and requires routine newborn care without major complications.",
    "type": "Definition",
    "important": false,
    "priority": "normal",
    "keywords": [
      "healthy newborn",
      "normal newborn",
      "term baby",
      "effective breathing"
    ],
    "cat": "Newborn Care",
    "q": "Define healthy newborn.",
    "a": "A healthy newborn is a baby born at or near term who establishes effective breathing, has stable vital functions and requires routine newborn care without major complications.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 47,
    "subject": "Newborn Care",
    "topic": "Essential Newborn Care",
    "question": "List four components of essential newborn care.",
    "answer": "1. Immediate drying and maintenance of warmth.\n2. Assessment of breathing and timely resuscitation if required.\n3. Early skin-to-skin contact.\n4. Early initiation of breastfeeding.",
    "type": "Essential Newborn Care",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "essential newborn care",
      "enc",
      "warmth",
      "resuscitation",
      "skin-to-skin",
      "breastfeeding"
    ],
    "cat": "Newborn Care",
    "q": "List four components of essential newborn care.",
    "a": "1. Immediate drying and maintenance of warmth.\n2. Assessment of breathing and timely resuscitation if required.\n3. Early skin-to-skin contact.\n4. Early initiation of breastfeeding.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 48,
    "subject": "Newborn Care",
    "topic": "Neonatal Asphyxia",
    "question": "Define neonatal asphyxia.",
    "answer": "Neonatal asphyxia refers to failure of a newborn to establish or maintain effective breathing at birth, requiring prompt assessment and appropriate resuscitation.",
    "type": "Definition",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "neonatal asphyxia",
      "birth asphyxia",
      "effective breathing",
      "resuscitation",
      "hypoxia"
    ],
    "cat": "Newborn Care",
    "q": "Define neonatal asphyxia.",
    "a": "Neonatal asphyxia refers to failure of a newborn to establish or maintain effective breathing at birth, requiring prompt assessment and appropriate resuscitation.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 49,
    "subject": "Newborn Care",
    "topic": "Immediate Measures in Asphyxia",
    "question": "State two immediate measures in neonatal asphyxia.",
    "answer": "1. Assess breathing and provide effective ventilation or resuscitation when indicated.\n2. Call for skilled assistance and continue neonatal resuscitation according to the recommended protocol.",
    "type": "Immediate Management",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "asphyxia management",
      "neonatal resuscitation",
      "ventilation",
      "skilled assistance"
    ],
    "cat": "Newborn Care",
    "q": "State two immediate measures in neonatal asphyxia.",
    "a": "1. Assess breathing and provide effective ventilation or resuscitation when indicated.\n2. Call for skilled assistance and continue neonatal resuscitation according to the recommended protocol.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 50,
    "subject": "Newborn Care",
    "topic": "Neonatal Respiratory Distress",
    "question": "Mention two signs of neonatal respiratory distress.",
    "answer": "1. Tachypnoea or abnormally rapid breathing.\n2. Chest retractions.\n\nOther signs include grunting and nasal flaring.",
    "type": "Signs",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "respiratory distress",
      "tachypnoea",
      "chest retractions",
      "grunting",
      "nasal flaring"
    ],
    "cat": "Newborn Care",
    "q": "Mention two signs of neonatal respiratory distress.",
    "a": "1. Tachypnoea or abnormally rapid breathing.\n2. Chest retractions.\n\nOther signs include grunting and nasal flaring.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 51,
    "subject": "Newborn Care",
    "topic": "Physiological Jaundice",
    "question": "What is physiological jaundice?",
    "answer": "Physiological jaundice is the common, usually self-limiting increase in unconjugated bilirubin occurring after birth because of normal newborn bilirubin production and immature hepatic processing.\n\nImportant point:\nIn a typical healthy term newborn, it usually becomes noticeable after the first 24 hours.",
    "type": "Definition",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "jaundice",
      "physiological jaundice",
      "unconjugated bilirubin",
      "hepatic processing",
      "after 24 hours"
    ],
    "cat": "Newborn Care",
    "q": "What is physiological jaundice?",
    "a": "Physiological jaundice is the common, usually self-limiting increase in unconjugated bilirubin occurring after birth because of normal newborn bilirubin production and immature hepatic processing.\n\nImportant point:\nIn a typical healthy term newborn, it usually becomes noticeable after the first 24 hours.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 52,
    "subject": "Newborn Care",
    "topic": "Features of Physiological Jaundice",
    "question": "Mention four features of physiological jaundice.",
    "answer": "1. Usually appears after the first 24 hours of life.\n2. It is predominantly due to increased unconjugated bilirubin.\n3. It reaches a peak during the early newborn period.\n4. It usually resolves spontaneously in healthy newborns.",
    "type": "Features",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "jaundice features",
      "physiological jaundice features",
      "after 24 hours",
      "unconjugated bilirubin"
    ],
    "cat": "Newborn Care",
    "q": "Mention four features of physiological jaundice.",
    "a": "1. Usually appears after the first 24 hours of life.\n2. It is predominantly due to increased unconjugated bilirubin.\n3. It reaches a peak during the early newborn period.\n4. It usually resolves spontaneously in healthy newborns.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 53,
    "subject": "Newborn Care",
    "topic": "Indications for Phototherapy",
    "question": "State two indications for phototherapy.",
    "answer": "1. Significant neonatal unconjugated hyperbilirubinaemia reaching the recommended treatment threshold.\n2. Bilirubin levels requiring treatment according to the baby's age in hours, gestational age and clinical risk factors.",
    "type": "Indications",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "phototherapy indications",
      "hyperbilirubinaemia",
      "treatment threshold",
      "bilirubin levels"
    ],
    "cat": "Newborn Care",
    "q": "State two indications for phototherapy.",
    "a": "1. Significant neonatal unconjugated hyperbilirubinaemia reaching the recommended treatment threshold.\n2. Bilirubin levels requiring treatment according to the baby's age in hours, gestational age and clinical risk factors.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 54,
    "subject": "Newborn Care",
    "topic": "Complications of Severe Jaundice",
    "question": "Name two complications of severe neonatal jaundice.",
    "answer": "1. Acute bilirubin encephalopathy.\n2. Kernicterus, which can cause permanent neurological damage.",
    "type": "Complications",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "jaundice complications",
      "bilirubin encephalopathy",
      "kernicterus",
      "neurological damage"
    ],
    "cat": "Newborn Care",
    "q": "Name two complications of severe neonatal jaundice.",
    "a": "1. Acute bilirubin encephalopathy.\n2. Kernicterus, which can cause permanent neurological damage.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 55,
    "subject": "Newborn Care",
    "topic": "Nursing Measures in Phototherapy",
    "question": "Mention two nursing measures for a newborn receiving phototherapy.",
    "answer": "1. Protect the newborn's eyes as prescribed and expose the appropriate skin surface to phototherapy.\n2. Monitor temperature, hydration, feeding, urine/stool output and bilirubin response.",
    "type": "Nursing Care",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "phototherapy nursing",
      "eye protection",
      "hydration",
      "temperature",
      "bilirubin response"
    ],
    "cat": "Newborn Care",
    "q": "Mention two nursing measures for a newborn receiving phototherapy.",
    "a": "1. Protect the newborn's eyes as prescribed and expose the appropriate skin surface to phototherapy.\n2. Monitor temperature, hydration, feeding, urine/stool output and bilirubin response.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 56,
    "subject": "Lactation & Breastfeeding",
    "topic": "Lactation",
    "question": "Define lactation.",
    "answer": "Lactation is the production and secretion of breast milk by the mammary glands after childbirth.\n\nImportant hormones:\n1. Prolactin mainly supports milk production.\n2. Oxytocin is responsible for milk ejection.",
    "type": "Definition",
    "important": true,
    "priority": "normal",
    "keywords": [
      "lactation",
      "milk production",
      "mammary glands",
      "prolactin",
      "oxytocin"
    ],
    "cat": "Lactation & Breastfeeding",
    "q": "Define lactation.",
    "a": "Lactation is the production and secretion of breast milk by the mammary glands after childbirth.\n\nImportant hormones:\n1. Prolactin mainly supports milk production.\n2. Oxytocin is responsible for milk ejection.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 57,
    "subject": "Lactation & Breastfeeding",
    "topic": "Advantages of Breastfeeding",
    "question": "Mention four advantages of breastfeeding.",
    "answer": "1. Provides appropriate nutrition for the infant.\n2. Provides antibodies and immune protection.\n3. Promotes mother–baby bonding.\n4. Helps protect the infant against several infections.",
    "type": "Advantages",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "breastfeeding advantages",
      "nutrition",
      "antibodies",
      "immune protection",
      "bonding",
      "infection"
    ],
    "cat": "Lactation & Breastfeeding",
    "q": "Mention four advantages of breastfeeding.",
    "a": "1. Provides appropriate nutrition for the infant.\n2. Provides antibodies and immune protection.\n3. Promotes mother–baby bonding.\n4. Helps protect the infant against several infections.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 58,
    "subject": "Lactation & Breastfeeding",
    "topic": "Benefits of Colostrum",
    "question": "State two benefits of colostrum.",
    "answer": "1. It is rich in antibodies and other immune protective factors.\n2. It provides concentrated nutrition and helps protect the newborn from infection.",
    "type": "Benefits",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "colostrum",
      "first milk",
      "antibodies",
      "immune protection",
      "concentrated nutrition"
    ],
    "cat": "Lactation & Breastfeeding",
    "q": "State two benefits of colostrum.",
    "a": "1. It is rich in antibodies and other immune protective factors.\n2. It provides concentrated nutrition and helps protect the newborn from infection.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 59,
    "subject": "Lactation & Breastfeeding",
    "topic": "Promoting Breastfeeding",
    "question": "List four factors that promote successful breastfeeding.",
    "answer": "1. Early initiation of breastfeeding.\n2. Correct positioning and attachment.\n3. Frequent breastfeeding according to the baby's needs.\n4. Proper education and skilled support for the mother.",
    "type": "Factors",
    "important": true,
    "priority": "important",
    "keywords": [
      "breastfeeding success",
      "early initiation",
      "positioning",
      "attachment",
      "frequent breastfeeding"
    ],
    "cat": "Lactation & Breastfeeding",
    "q": "List four factors that promote successful breastfeeding.",
    "a": "1. Early initiation of breastfeeding.\n2. Correct positioning and attachment.\n3. Frequent breastfeeding according to the baby's needs.\n4. Proper education and skilled support for the mother.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 60,
    "subject": "Lactation & Breastfeeding",
    "topic": "Hormones of Lactation",
    "question": "Name two hormones involved in lactation.",
    "answer": "1. Prolactin – mainly responsible for milk production.\n2. Oxytocin – responsible for milk ejection or let-down.",
    "type": "Name",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "lactation hormones",
      "prolactin",
      "oxytocin",
      "milk production",
      "milk ejection",
      "let-down"
    ],
    "cat": "Lactation & Breastfeeding",
    "q": "Name two hormones involved in lactation.",
    "a": "1. Prolactin – mainly responsible for milk production.\n2. Oxytocin – responsible for milk ejection or let-down.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 61,
    "subject": "Community Health Nursing II",
    "topic": "Primary Health Care (PHC)",
    "question": "Define primary health care.",
    "answer": "Primary health care is essential health care made universally accessible to individuals and families in the community through acceptable methods, with their participation and at a cost the community and country can afford.\n\nImportant point:\nIt is the first level of contact between individuals and the health-care system.",
    "type": "Definition",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "primary health care",
      "phc",
      "essential health care",
      "universally accessible",
      "first level contact"
    ],
    "cat": "Community Health Nursing II",
    "q": "Define primary health care.",
    "a": "Primary health care is essential health care made universally accessible to individuals and families in the community through acceptable methods, with their participation and at a cost the community and country can afford.\n\nImportant point:\nIt is the first level of contact between individuals and the health-care system.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 62,
    "subject": "Community Health Nursing II",
    "topic": "Principles of Primary Health Care",
    "question": "Mention four principles of primary health care.",
    "answer": "1. Equitable distribution.\n2. Community participation.\n3. Intersectoral coordination.\n4. Appropriate technology.",
    "type": "Principles",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "phc principles",
      "equitable distribution",
      "community participation",
      "intersectoral coordination",
      "appropriate technology"
    ],
    "cat": "Community Health Nursing II",
    "q": "Mention four principles of primary health care.",
    "a": "1. Equitable distribution.\n2. Community participation.\n3. Intersectoral coordination.\n4. Appropriate technology.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 63,
    "subject": "Community Health Nursing II",
    "topic": "Functions of Primary Health Centre",
    "question": "List four functions of a Primary Health Centre.",
    "answer": "1. Provide maternal and child health services.\n2. Provide treatment for common illnesses and minor conditions.\n3. Conduct disease prevention and control activities.\n4. Provide health education and referral services.",
    "type": "Functions",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "phc functions",
      "primary health centre",
      "mch services",
      "disease prevention",
      "health education"
    ],
    "cat": "Community Health Nursing II",
    "q": "List four functions of a Primary Health Centre.",
    "a": "1. Provide maternal and child health services.\n2. Provide treatment for common illnesses and minor conditions.\n3. Conduct disease prevention and control activities.\n4. Provide health education and referral services.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 64,
    "subject": "Community Health Nursing II",
    "topic": "School Health Services",
    "question": "State two objectives of school health services.",
    "answer": "1. To promote and maintain the physical and mental health of school children.\n2. To detect health problems early and provide appropriate treatment, referral and follow-up.",
    "type": "Objectives",
    "important": false,
    "priority": "important",
    "keywords": [
      "school health",
      "school health objectives",
      "early detection",
      "referral",
      "children health"
    ],
    "cat": "Community Health Nursing II",
    "q": "State two objectives of school health services.",
    "a": "1. To promote and maintain the physical and mental health of school children.\n2. To detect health problems early and provide appropriate treatment, referral and follow-up.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 65,
    "subject": "Community Health Nursing II",
    "topic": "Methods of Health Education",
    "question": "Mention two methods of health education.",
    "answer": "1. Individual method – individual teaching or counselling.\n2. Group method – group discussion, demonstration or health talk.",
    "type": "Methods",
    "important": false,
    "priority": "important",
    "keywords": [
      "health education methods",
      "individual method",
      "group method",
      "counselling",
      "demonstration"
    ],
    "cat": "Community Health Nursing II",
    "q": "Mention two methods of health education.",
    "a": "1. Individual method – individual teaching or counselling.\n2. Group method – group discussion, demonstration or health talk.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 66,
    "subject": "Community Health Nursing II",
    "topic": "Family Planning",
    "question": "Define family planning.",
    "answer": "Family planning is the voluntary process through which individuals or couples decide the number and spacing of their children and select suitable methods of contraception.",
    "type": "Definition",
    "important": true,
    "priority": "important",
    "keywords": [
      "family planning",
      "spacing",
      "contraception",
      "voluntary process"
    ],
    "cat": "Community Health Nursing II",
    "q": "Define family planning.",
    "a": "Family planning is the voluntary process through which individuals or couples decide the number and spacing of their children and select suitable methods of contraception.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 67,
    "subject": "Community Health Nursing II",
    "topic": "Temporary Contraception",
    "question": "Mention four temporary contraceptive methods.",
    "answer": "1. Condoms.\n2. Oral contraceptive pills.\n3. Intrauterine contraceptive devices.\n4. Injectable contraceptives.",
    "type": "Methods",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "temporary contraception",
      "condoms",
      "oral contraceptive pills",
      "iud",
      "injectable contraceptives"
    ],
    "cat": "Community Health Nursing II",
    "q": "Mention four temporary contraceptive methods.",
    "a": "1. Condoms.\n2. Oral contraceptive pills.\n3. Intrauterine contraceptive devices.\n4. Injectable contraceptives.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 68,
    "subject": "Community Health Nursing II",
    "topic": "Permanent Contraception",
    "question": "Name two permanent methods of contraception.",
    "answer": "1. Female sterilization – tubal occlusion or tubectomy.\n2. Male sterilization – vasectomy.",
    "type": "Methods",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "permanent contraception",
      "female sterilization",
      "tubectomy",
      "vasectomy",
      "male sterilization"
    ],
    "cat": "Community Health Nursing II",
    "q": "Name two permanent methods of contraception.",
    "a": "1. Female sterilization – tubal occlusion or tubectomy.\n2. Male sterilization – vasectomy.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 69,
    "subject": "Community Health Nursing II",
    "topic": "Objectives of Family Planning",
    "question": "State two objectives of family planning.",
    "answer": "1. To promote healthy spacing and timing of pregnancies.\n2. To prevent unintended pregnancies and reduce associated maternal and child health risks.",
    "type": "Objectives",
    "important": false,
    "priority": "important",
    "keywords": [
      "family planning objectives",
      "spacing pregnancies",
      "unintended pregnancies",
      "maternal risk"
    ],
    "cat": "Community Health Nursing II",
    "q": "State two objectives of family planning.",
    "a": "1. To promote healthy spacing and timing of pregnancies.\n2. To prevent unintended pregnancies and reduce associated maternal and child health risks.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 70,
    "subject": "Community Health Nursing II",
    "topic": "Birth Preparedness",
    "question": "Mention two benefits of birth preparedness.",
    "answer": "1. Helps the mother and family plan for skilled birth attendance and necessary supplies.\n2. Helps arrange transport, financial resources and emergency referral plans in advance.",
    "type": "Benefits",
    "important": false,
    "priority": "important",
    "keywords": [
      "birth preparedness",
      "skilled birth attendance",
      "transport",
      "emergency referral",
      "supplies"
    ],
    "cat": "Community Health Nursing II",
    "q": "Mention two benefits of birth preparedness.",
    "a": "1. Helps the mother and family plan for skilled birth attendance and necessary supplies.\n2. Helps arrange transport, financial resources and emergency referral plans in advance.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 71,
    "subject": "Nursing Research & Statistics",
    "topic": "Nursing Research",
    "question": "Define nursing research.",
    "answer": "Nursing research is a systematic scientific investigation conducted to develop, validate or apply knowledge that improves nursing practice, education, administration and patient care.",
    "type": "Definition",
    "important": true,
    "priority": "important",
    "keywords": [
      "nursing research",
      "scientific investigation",
      "nursing practice",
      "patient care"
    ],
    "cat": "Nursing Research & Statistics",
    "q": "Define nursing research.",
    "a": "Nursing research is a systematic scientific investigation conducted to develop, validate or apply knowledge that improves nursing practice, education, administration and patient care.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 72,
    "subject": "Nursing Research & Statistics",
    "topic": "Research Problem Characteristics",
    "question": "Mention two characteristics of a good research problem.",
    "answer": "1. It should be clear, specific and researchable.\n2. It should be feasible, relevant and possible to investigate using available time and resources.",
    "type": "Characteristics",
    "important": false,
    "priority": "important",
    "keywords": [
      "research problem",
      "researchable",
      "feasible",
      "relevant",
      "clear"
    ],
    "cat": "Nursing Research & Statistics",
    "q": "Mention two characteristics of a good research problem.",
    "a": "1. It should be clear, specific and researchable.\n2. It should be feasible, relevant and possible to investigate using available time and resources.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 73,
    "subject": "Nursing Research & Statistics",
    "topic": "Sources of Research Problem",
    "question": "List four sources of a research problem.",
    "answer": "1. Clinical practice.\n2. Previous research and literature.\n3. Nursing theories.\n4. Personal observations and professional experience.",
    "type": "Sources",
    "important": true,
    "priority": "important",
    "keywords": [
      "research problem sources",
      "clinical practice",
      "literature",
      "nursing theories",
      "observations"
    ],
    "cat": "Nursing Research & Statistics",
    "q": "List four sources of a research problem.",
    "a": "1. Clinical practice.\n2. Previous research and literature.\n3. Nursing theories.\n4. Personal observations and professional experience.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 74,
    "subject": "Nursing Research & Statistics",
    "topic": "Research Design",
    "question": "Define research design.",
    "answer": "Research design is the overall plan or blueprint of a research study that specifies how the study will be conducted, including sampling, data collection, measurement and analysis.",
    "type": "Definition",
    "important": true,
    "priority": "important",
    "keywords": [
      "research design",
      "blueprint",
      "overall plan",
      "methodology",
      "sampling",
      "data collection"
    ],
    "cat": "Nursing Research & Statistics",
    "q": "Define research design.",
    "a": "Research design is the overall plan or blueprint of a research study that specifies how the study will be conducted, including sampling, data collection, measurement and analysis.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 75,
    "subject": "Nursing Research & Statistics",
    "topic": "Data Collection Methods",
    "question": "Name two methods of data collection.",
    "answer": "1. Questionnaire or interview.\n2. Observation.\n\nOther methods may include measurements, records and document review.",
    "type": "Methods",
    "important": false,
    "priority": "important",
    "keywords": [
      "data collection methods",
      "questionnaire",
      "interview",
      "observation",
      "records"
    ],
    "cat": "Nursing Research & Statistics",
    "q": "Name two methods of data collection.",
    "a": "1. Questionnaire or interview.\n2. Observation.\n\nOther methods may include measurements, records and document review.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 76,
    "subject": "Nursing Research & Statistics",
    "topic": "Hypothesis",
    "question": "Define hypothesis.",
    "answer": "A hypothesis is a tentative, clear and testable statement that predicts a relationship or difference between two or more variables.",
    "type": "Definition",
    "important": true,
    "priority": "important",
    "keywords": [
      "hypothesis",
      "testable statement",
      "variables",
      "tentative prediction"
    ],
    "cat": "Nursing Research & Statistics",
    "q": "Define hypothesis.",
    "a": "A hypothesis is a tentative, clear and testable statement that predicts a relationship or difference between two or more variables.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 77,
    "subject": "Nursing Research & Statistics",
    "topic": "Population and Sample",
    "question": "Define population and sample.",
    "answer": "Population:\nThe complete group of individuals, objects or units to which the researcher wants to apply the findings.\n\nSample:\nA selected subset of the population that is studied to obtain information about the population.",
    "type": "Definition",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "population",
      "sample",
      "target population",
      "subset",
      "sampling"
    ],
    "cat": "Nursing Research & Statistics",
    "q": "Define population and sample.",
    "a": "Population:\nThe complete group of individuals, objects or units to which the researcher wants to apply the findings.\n\nSample:\nA selected subset of the population that is studied to obtain information about the population.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 78,
    "subject": "Nursing Research & Statistics",
    "topic": "Probability Sampling Methods",
    "question": "Name four probability sampling methods.",
    "answer": "1. Simple random sampling.\n2. Systematic sampling.\n3. Stratified random sampling.\n4. Cluster sampling.",
    "type": "Methods",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "sampling",
      "probability sampling",
      "simple random",
      "systematic",
      "stratified random",
      "cluster"
    ],
    "cat": "Nursing Research & Statistics",
    "q": "Name four probability sampling methods.",
    "a": "1. Simple random sampling.\n2. Systematic sampling.\n3. Stratified random sampling.\n4. Cluster sampling.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 79,
    "subject": "Nursing Research & Statistics",
    "topic": "Data Presentation Methods",
    "question": "Mention two methods of presenting data.",
    "answer": "1. Tabular presentation – presenting information in tables.\n2. Graphical or diagrammatic presentation – presenting information using graphs or diagrams.",
    "type": "Methods",
    "important": false,
    "priority": "important",
    "keywords": [
      "data presentation",
      "tabular presentation",
      "graphical presentation",
      "tables",
      "graphs"
    ],
    "cat": "Nursing Research & Statistics",
    "q": "Mention two methods of presenting data.",
    "a": "1. Tabular presentation – presenting information in tables.\n2. Graphical or diagrammatic presentation – presenting information using graphs or diagrams.",
    "starred": false,
    "mastered": false
  },
  {
    "id": 80,
    "subject": "Nursing Research & Statistics",
    "topic": "Arithmetic Mean",
    "question": "Define mean.",
    "answer": "The arithmetic mean is the average value of a set of observations.\n\nFormula:\n\nMean = Sum of all observations ÷ Number of observations\n\nExample:\n\nIf the observations are 2, 4 and 6:\n\nMean = (2 + 4 + 6) ÷ 3 = 4",
    "type": "Definition",
    "important": true,
    "priority": "high-yield",
    "keywords": [
      "mean",
      "arithmetic mean",
      "average",
      "statistics",
      "observations",
      "formula"
    ],
    "cat": "Nursing Research & Statistics",
    "q": "Define mean.",
    "a": "The arithmetic mean is the average value of a set of observations.\n\nFormula:\n\nMean = Sum of all observations ÷ Number of observations\n\nExample:\n\nIf the observations are 2, 4 and 6:\n\nMean = (2 + 4 + 6) ÷ 3 = 4",
    "starred": false,
    "mastered": false
  }
];

if (typeof window !== 'undefined') {
  window.QUESTIONS = QUESTIONS;
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { QUESTIONS };
}
