const MCQ_QUESTIONS = [
  {
    "id": "mcq-001",
    "mcqNumber": 1,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Anatomy, Pregnancy & Placenta",
    "subject": "Anatomy, Pregnancy & Placenta",
    "topic": "Anatomy, Pregnancy & Placenta",
    "question": "Bartholin gland is located in the:",
    "options": [
      "Cervix",
      "Ovary",
      "Vagina",
      "Uterus"
    ],
    "correctAnswer": 2,
    "correctAnswerText": "Vagina",
    "explanation": "The correct answer is Vagina."
  },
  {
    "id": "mcq-002",
    "mcqNumber": 2,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Uterus",
    "subject": "Uterus",
    "topic": "Uterus",
    "question": "The ovarian artery arises directly from the:",
    "options": [
      "Renal artery",
      "Internal iliac artery",
      "Abdominal aorta",
      "External iliac artery"
    ],
    "correctAnswer": 2,
    "correctAnswerText": "Abdominal aorta",
    "explanation": "The correct answer is Abdominal aorta."
  },
  {
    "id": "mcq-003",
    "mcqNumber": 3,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "External iliac artery",
    "subject": "External iliac artery",
    "topic": "External iliac artery",
    "question": "The normal shape of the female pelvis most favourable for vaginal delivery is:",
    "options": [
      "Android",
      "Anthropoid",
      "Platypelloid",
      "Gynaecoid"
    ],
    "correctAnswer": 3,
    "correctAnswerText": "Gynaecoid",
    "explanation": "The correct answer is Gynaecoid."
  },
  {
    "id": "mcq-004",
    "mcqNumber": 4,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Gynaecoid",
    "subject": "Gynaecoid",
    "topic": "Gynaecoid",
    "question": "The uterus is normally situated between the:",
    "options": [
      "Bladder and rectum",
      "Kidney and bladder",
      "Rectum and kidney",
      "Ovary and bladder"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Bladder and rectum",
    "explanation": "The correct answer is Bladder and rectum."
  },
  {
    "id": "mcq-005",
    "mcqNumber": 5,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Ovary and bladder",
    "subject": "Ovary and bladder",
    "topic": "Ovary and bladder",
    "question": "The main function of the placenta is:",
    "options": [
      "Digestion",
      "Exchange between mother and fetus",
      "Urine formation",
      "Blood clotting"
    ],
    "correctAnswer": 1,
    "correctAnswerText": "Exchange between mother and fetus",
    "explanation": "The correct answer is Exchange between mother and fetus."
  },
  {
    "id": "mcq-006",
    "mcqNumber": 6,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Blood clotting",
    "subject": "Blood clotting",
    "topic": "Blood clotting",
    "question": "The fetal part of placenta is formed by the:",
    "options": [
      "Decidua basalis",
      "Chorion frondosum",
      "Endometrium",
      "Myometrium"
    ],
    "correctAnswer": 1,
    "correctAnswerText": "Chorion frondosum",
    "explanation": "The correct answer is Chorion frondosum."
  },
  {
    "id": "mcq-007",
    "mcqNumber": 7,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Myometrium",
    "subject": "Myometrium",
    "topic": "Myometrium",
    "question": "The maternal part of placenta is formed by the:",
    "options": [
      "Chorion",
      "Amnion",
      "Decidua basalis",
      "Yolk sac"
    ],
    "correctAnswer": 2,
    "correctAnswerText": "Decidua basalis",
    "explanation": "The correct answer is Decidua basalis."
  },
  {
    "id": "mcq-008",
    "mcqNumber": 8,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Yolk sac",
    "subject": "Yolk sac",
    "topic": "Yolk sac",
    "question": "The normal umbilical cord contains:",
    "options": [
      "One artery and one vein",
      "Two arteries and one vein",
      "Two veins and one artery",
      "Three arteries"
    ],
    "correctAnswer": 1,
    "correctAnswerText": "Two arteries and one vein",
    "explanation": "The correct answer is Two arteries and one vein."
  },
  {
    "id": "mcq-009",
    "mcqNumber": 9,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Three arteries",
    "subject": "Three arteries",
    "topic": "Three arteries",
    "question": "The normal number of umbilical cord vessels is:",
    "options": [
      "1",
      "2",
      "3",
      "4"
    ],
    "correctAnswer": 2,
    "correctAnswerText": "3",
    "explanation": "The correct answer is 3."
  },
  {
    "id": "mcq-010",
    "mcqNumber": 10,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "4",
    "subject": "4",
    "topic": "4",
    "question": "The hormone mainly responsible for maintenance of pregnancy is:",
    "options": [
      "Progesterone",
      "Oxytocin",
      "FSH",
      "Prolactin"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Progesterone",
    "explanation": "The correct answer is Progesterone."
  },
  {
    "id": "mcq-011",
    "mcqNumber": 11,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Prolactin",
    "subject": "Prolactin",
    "topic": "Prolactin",
    "question": "The hormone detected by most pregnancy tests is:",
    "options": [
      "Estrogen",
      "Progesterone",
      "hCG",
      "Oxytocin"
    ],
    "correctAnswer": 2,
    "correctAnswerText": "hCG",
    "explanation": "The correct answer is hCG."
  },
  {
    "id": "mcq-012",
    "mcqNumber": 12,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Oxytocin",
    "subject": "Oxytocin",
    "topic": "Oxytocin",
    "question": "hCG is secreted mainly by the:",
    "options": [
      "Myometrium",
      "Trophoblast",
      "Ovary",
      "Pituitary gland"
    ],
    "correctAnswer": 1,
    "correctAnswerText": "Trophoblast",
    "explanation": "The correct answer is Trophoblast."
  },
  {
    "id": "mcq-013",
    "mcqNumber": 13,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Pituitary gland",
    "subject": "Pituitary gland",
    "topic": "Pituitary gland",
    "question": "The average duration of pregnancy is approximately:",
    "options": [
      "28 weeks",
      "32 weeks",
      "36 weeks",
      "40 weeks"
    ],
    "correctAnswer": 3,
    "correctAnswerText": "40 weeks",
    "explanation": "The correct answer is 40 weeks."
  },
  {
    "id": "mcq-014",
    "mcqNumber": 14,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "40 weeks",
    "subject": "40 weeks",
    "topic": "40 weeks",
    "question": "The first trimester extends up to:",
    "options": [
      "8 weeks",
      "12 weeks",
      "20 weeks",
      "28 weeks"
    ],
    "correctAnswer": 1,
    "correctAnswerText": "12 weeks",
    "explanation": "The correct answer is 12 weeks."
  },
  {
    "id": "mcq-015",
    "mcqNumber": 15,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "28 weeks",
    "subject": "28 weeks",
    "topic": "28 weeks",
    "question": "Bluish discoloration of the vagina and cervix in early pregnancy is called:",
    "options": [
      "Goodell sign",
      "Hegar sign",
      "Chadwick sign",
      "Ballottement"
    ],
    "correctAnswer": 2,
    "correctAnswerText": "Chadwick sign",
    "explanation": "The correct answer is Chadwick sign."
  },
  {
    "id": "mcq-016",
    "mcqNumber": 16,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Ballottement",
    "subject": "Ballottement",
    "topic": "Ballottement",
    "question": "Softening of the cervix is known as:",
    "options": [
      "Hegar sign",
      "Goodell sign",
      "Chadwick sign",
      "Braxton Hicks sign"
    ],
    "correctAnswer": 1,
    "correctAnswerText": "Goodell sign",
    "explanation": "The correct answer is Goodell sign."
  },
  {
    "id": "mcq-017",
    "mcqNumber": 17,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Braxton Hicks sign",
    "subject": "Braxton Hicks sign",
    "topic": "Braxton Hicks sign",
    "question": "Softening of the uterine isthmus is known as:",
    "options": [
      "Hegar sign",
      "Goodell sign",
      "Chadwick sign",
      "Piskacek sign"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Hegar sign",
    "explanation": "The correct answer is Hegar sign."
  },
  {
    "id": "mcq-018",
    "mcqNumber": 18,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Piskacek sign",
    "subject": "Piskacek sign",
    "topic": "Piskacek sign",
    "question": "The first fetal movement perceived by the mother is called:",
    "options": [
      "Ballottement",
      "Quickening",
      "Lightening",
      "Engagement"
    ],
    "correctAnswer": 1,
    "correctAnswerText": "Quickening",
    "explanation": "The correct answer is Quickening."
  },
  {
    "id": "mcq-019",
    "mcqNumber": 19,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Engagement",
    "subject": "Engagement",
    "topic": "Engagement",
    "question": "The usual site of implantation is the:",
    "options": [
      "Cervix",
      "Lower uterine segment",
      "Upper posterior uterine wall",
      "Vagina"
    ],
    "correctAnswer": 2,
    "correctAnswerText": "Upper posterior uterine wall",
    "explanation": "The correct answer is Upper posterior uterine wall."
  },
  {
    "id": "mcq-020",
    "mcqNumber": 20,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Vagina",
    "subject": "Vagina",
    "topic": "Vagina",
    "question": "Fertilization normally occurs in the:",
    "options": [
      "Uterus",
      "Cervix",
      "Ampulla of fallopian tube",
      "Vagina"
    ],
    "correctAnswer": 2,
    "correctAnswerText": "Ampulla of fallopian tube",
    "explanation": "The correct answer is Ampulla of fallopian tube."
  },
  {
    "id": "mcq-021",
    "mcqNumber": 21,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Antenatal Care",
    "subject": "Antenatal Care",
    "topic": "Antenatal Care",
    "question": "ANC stands for:",
    "options": [
      "Advanced Neonatal Care",
      "Antenatal Care",
      "Antenatal Consultation",
      "Advanced Nursing Care"
    ],
    "correctAnswer": 1,
    "correctAnswerText": "Antenatal Care",
    "explanation": "The correct answer is Antenatal Care."
  },
  {
    "id": "mcq-022",
    "mcqNumber": 22,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Advanced Nursing Care",
    "subject": "Advanced Nursing Care",
    "topic": "Advanced Nursing Care",
    "question": "The main purpose of antenatal care is to:",
    "options": [
      "Treat only complications",
      "Promote maternal and fetal health",
      "Perform surgery",
      "Prevent breastfeeding"
    ],
    "correctAnswer": 1,
    "correctAnswerText": "Promote maternal and fetal health",
    "explanation": "The correct answer is Promote maternal and fetal health."
  },
  {
    "id": "mcq-023",
    "mcqNumber": 23,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Prevent breastfeeding",
    "subject": "Prevent breastfeeding",
    "topic": "Prevent breastfeeding",
    "question": "Blood pressure is routinely assessed during ANC mainly to detect:",
    "options": [
      "Anaemia",
      "Hypertension/pre-eclampsia",
      "Diabetes only",
      "Infection only"
    ],
    "correctAnswer": 1,
    "correctAnswerText": "Hypertension/pre-eclampsia",
    "explanation": "The correct answer is Hypertension/pre-eclampsia."
  },
  {
    "id": "mcq-024",
    "mcqNumber": 24,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Infection only",
    "subject": "Infection only",
    "topic": "Infection only",
    "question": "Protein in urine during pregnancy is assessed mainly in relation to:",
    "options": [
      "Anaemia",
      "Pre-eclampsia",
      "GDM",
      "Hyperemesis"
    ],
    "correctAnswer": 1,
    "correctAnswerText": "Pre-eclampsia",
    "explanation": "The correct answer is Pre-eclampsia."
  },
  {
    "id": "mcq-025",
    "mcqNumber": 25,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Hyperemesis",
    "subject": "Hyperemesis",
    "topic": "Hyperemesis",
    "question": "A pregnant woman should receive advice regarding:",
    "options": [
      "Nutrition",
      "Danger signs",
      "Birth preparedness",
      "All of the above"
    ],
    "correctAnswer": 3,
    "correctAnswerText": "All of the above",
    "explanation": "The correct answer is All of the above."
  },
  {
    "id": "mcq-026",
    "mcqNumber": 26,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "All of the above",
    "subject": "All of the above",
    "topic": "All of the above",
    "question": "One important component of antenatal assessment is:",
    "options": [
      "Fundal height",
      "Hair colour",
      "Shoe size",
      "Eye colour"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Fundal height",
    "explanation": "The correct answer is Fundal height."
  },
  {
    "id": "mcq-027",
    "mcqNumber": 27,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Eye colour",
    "subject": "Eye colour",
    "topic": "Eye colour",
    "question": "Fetal heart rate is an important indicator of:",
    "options": [
      "Maternal nutrition",
      "Fetal well-being",
      "Cervical maturity",
      "Placental weight"
    ],
    "correctAnswer": 1,
    "correctAnswerText": "Fetal well-being",
    "explanation": "The correct answer is Fetal well-being."
  },
  {
    "id": "mcq-028",
    "mcqNumber": 28,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Placental weight",
    "subject": "Placental weight",
    "topic": "Placental weight",
    "question": "Normal fetal heart rate is approximately:",
    "options": [
      "60–90/min",
      "90–110/min",
      "110–160/min",
      "170–220/min"
    ],
    "correctAnswer": 2,
    "correctAnswerText": "110–160/min",
    "explanation": "The correct answer is 110–160/min."
  },
  {
    "id": "mcq-029",
    "mcqNumber": 29,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "170–220/min",
    "subject": "170–220/min",
    "topic": "170–220/min",
    "question": "Iron supplementation during pregnancy primarily prevents:",
    "options": [
      "Hypertension",
      "Iron-deficiency anaemia",
      "Diabetes",
      "Jaundice"
    ],
    "correctAnswer": 1,
    "correctAnswerText": "Iron-deficiency anaemia",
    "explanation": "The correct answer is Iron-deficiency anaemia."
  },
  {
    "id": "mcq-030",
    "mcqNumber": 30,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Jaundice",
    "subject": "Jaundice",
    "topic": "Jaundice",
    "question": "Folic acid supplementation helps prevent:",
    "options": [
      "Neural tube defects",
      "PPH",
      "Placenta previa",
      "Eclampsia"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Neural tube defects",
    "explanation": "The correct answer is Neural tube defects."
  },
  {
    "id": "mcq-031",
    "mcqNumber": 31,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Anaemia & GDM",
    "subject": "Anaemia & GDM",
    "topic": "Anaemia & GDM",
    "question": "Anaemia in pregnancy is commonly associated with deficiency of:",
    "options": [
      "Iron",
      "Sodium",
      "Calcium only",
      "Vitamin K only"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Iron",
    "explanation": "The correct answer is Iron."
  },
  {
    "id": "mcq-032",
    "mcqNumber": 32,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Vitamin K only",
    "subject": "Vitamin K only",
    "topic": "Vitamin K only",
    "question": "The most common nutritional anaemia in pregnancy is:",
    "options": [
      "Iron-deficiency anaemia",
      "Sickle cell anaemia",
      "Aplastic anaemia",
      "Haemolytic anaemia"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Iron-deficiency anaemia",
    "explanation": "The correct answer is Iron-deficiency anaemia."
  },
  {
    "id": "mcq-033",
    "mcqNumber": 33,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Haemolytic anaemia",
    "subject": "Haemolytic anaemia",
    "topic": "Haemolytic anaemia",
    "question": "A common symptom of anaemia is:",
    "options": [
      "Pallor",
      "Hypertension",
      "Jaundice always",
      "Bradycardia"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Pallor",
    "explanation": "The correct answer is Pallor."
  },
  {
    "id": "mcq-034",
    "mcqNumber": 34,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Bradycardia",
    "subject": "Bradycardia",
    "topic": "Bradycardia",
    "question": "GDM stands for:",
    "options": [
      "General Diabetes Management",
      "Gestational Diabetes Mellitus",
      "Gestational Digestive Malfunction",
      "General Dietary Management"
    ],
    "correctAnswer": 1,
    "correctAnswerText": "Gestational Diabetes Mellitus",
    "explanation": "The correct answer is Gestational Diabetes Mellitus."
  },
  {
    "id": "mcq-035",
    "mcqNumber": 35,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "General Dietary Management",
    "subject": "General Dietary Management",
    "topic": "General Dietary Management",
    "question": "GDM is diabetes first recognized during:",
    "options": [
      "Childhood",
      "Pregnancy",
      "Menopause",
      "Lactation only"
    ],
    "correctAnswer": 1,
    "correctAnswerText": "Pregnancy",
    "explanation": "The correct answer is Pregnancy."
  },
  {
    "id": "mcq-036",
    "mcqNumber": 36,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Lactation only",
    "subject": "Lactation only",
    "topic": "Lactation only",
    "question": "A major fetal complication associated with maternal diabetes is:",
    "options": [
      "Macrosomia",
      "Microcephaly always",
      "Club foot always",
      "Low maternal BP"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Macrosomia",
    "explanation": "The correct answer is Macrosomia."
  },
  {
    "id": "mcq-037",
    "mcqNumber": 37,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Low maternal BP",
    "subject": "Low maternal BP",
    "topic": "Low maternal BP",
    "question": "The first-line management of many women with GDM includes:",
    "options": [
      "Dietary modification",
      "Complete fasting",
      "Antibiotics",
      "Sedatives"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Dietary modification",
    "explanation": "The correct answer is Dietary modification."
  },
  {
    "id": "mcq-038",
    "mcqNumber": 38,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Sedatives",
    "subject": "Sedatives",
    "topic": "Sedatives",
    "question": "Blood glucose monitoring in GDM is important to:",
    "options": [
      "Assess glycaemic control",
      "Measure fetal weight directly",
      "Diagnose placenta previa",
      "Determine pelvic type"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Assess glycaemic control",
    "explanation": "The correct answer is Assess glycaemic control."
  },
  {
    "id": "mcq-039",
    "mcqNumber": 39,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Determine pelvic type",
    "subject": "Determine pelvic type",
    "topic": "Determine pelvic type",
    "question": "A newborn of a diabetic mother is at increased risk of:",
    "options": [
      "Hypoglycaemia",
      "Maternal hypertension",
      "Placenta previa",
      "Eclampsia"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Hypoglycaemia",
    "explanation": "The correct answer is Hypoglycaemia."
  },
  {
    "id": "mcq-040",
    "mcqNumber": 40,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Eclampsia",
    "subject": "Eclampsia",
    "topic": "Eclampsia",
    "question": "GDM may increase the risk of:",
    "options": [
      "Macrosomia",
      "Shoulder dystocia",
      "Neonatal hypoglycaemia",
      "All of the above"
    ],
    "correctAnswer": 3,
    "correctAnswerText": "All of the above",
    "explanation": "The correct answer is All of the above."
  },
  {
    "id": "mcq-041",
    "mcqNumber": 41,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Normal Labour",
    "subject": "Normal Labour",
    "topic": "Normal Labour",
    "question": "Labour is characterized by:",
    "options": [
      "Regular uterine contractions with cervical changes",
      "Only backache",
      "Only fetal movement",
      "Only vaginal discharge"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Regular uterine contractions with cervical changes",
    "explanation": "The correct answer is Regular uterine contractions with cervical changes."
  },
  {
    "id": "mcq-042",
    "mcqNumber": 42,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Only vaginal discharge",
    "subject": "Only vaginal discharge",
    "topic": "Only vaginal discharge",
    "question": "The first stage of labour ends with:",
    "options": [
      "Onset of contractions",
      "Full cervical dilatation",
      "Birth of baby",
      "Delivery of placenta"
    ],
    "correctAnswer": 1,
    "correctAnswerText": "Full cervical dilatation",
    "explanation": "The correct answer is Full cervical dilatation."
  },
  {
    "id": "mcq-043",
    "mcqNumber": 43,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Delivery of placenta",
    "subject": "Delivery of placenta",
    "topic": "Delivery of placenta",
    "question": "Full cervical dilatation is approximately:",
    "options": [
      "2 cm",
      "5 cm",
      "8 cm",
      "10 cm"
    ],
    "correctAnswer": 3,
    "correctAnswerText": "10 cm",
    "explanation": "The correct answer is 10 cm."
  },
  {
    "id": "mcq-044",
    "mcqNumber": 44,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "10 cm",
    "subject": "10 cm",
    "topic": "10 cm",
    "question": "The second stage of labour ends with:",
    "options": [
      "Full cervical dilatation",
      "Birth of the baby",
      "Delivery of placenta",
      "Uterine involution"
    ],
    "correctAnswer": 1,
    "correctAnswerText": "Birth of the baby",
    "explanation": "The correct answer is Birth of the baby."
  },
  {
    "id": "mcq-045",
    "mcqNumber": 45,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Uterine involution",
    "subject": "Uterine involution",
    "topic": "Uterine involution",
    "question": "The third stage of labour involves:",
    "options": [
      "Cervical dilatation",
      "Delivery of placenta",
      "Birth of baby",
      "Breastfeeding"
    ],
    "correctAnswer": 1,
    "correctAnswerText": "Delivery of placenta",
    "explanation": "The correct answer is Delivery of placenta."
  },
  {
    "id": "mcq-046",
    "mcqNumber": 46,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Breastfeeding",
    "subject": "Breastfeeding",
    "topic": "Breastfeeding",
    "question": "The fourth stage of labour mainly refers to:",
    "options": [
      "First trimester",
      "Immediate postpartum observation",
      "Placental development",
      "Implantation"
    ],
    "correctAnswer": 1,
    "correctAnswerText": "Immediate postpartum observation",
    "explanation": "The correct answer is Immediate postpartum observation."
  },
  {
    "id": "mcq-047",
    "mcqNumber": 47,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Implantation",
    "subject": "Implantation",
    "topic": "Implantation",
    "question": "True labour pain is usually associated with:",
    "options": [
      "Progressive cervical dilatation",
      "No cervical change",
      "Decreasing intensity",
      "Complete absence of contractions"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Progressive cervical dilatation",
    "explanation": "The correct answer is Progressive cervical dilatation."
  },
  {
    "id": "mcq-048",
    "mcqNumber": 48,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Complete absence of contractions",
    "subject": "Complete absence of contractions",
    "topic": "Complete absence of contractions",
    "question": "False labour pains generally:",
    "options": [
      "Become progressively stronger",
      "Produce progressive cervical dilatation",
      "Are irregular and do not cause progressive cervical change",
      "Always lead to delivery"
    ],
    "correctAnswer": 2,
    "correctAnswerText": "Are irregular and do not cause progressive cervical change",
    "explanation": "The correct answer is Are irregular and do not cause progressive cervical change."
  },
  {
    "id": "mcq-049",
    "mcqNumber": 49,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Always lead to delivery",
    "subject": "Always lead to delivery",
    "topic": "Always lead to delivery",
    "question": "The presenting part most commonly seen in normal labour is:",
    "options": [
      "Breech",
      "Shoulder",
      "Vertex",
      "Face"
    ],
    "correctAnswer": 2,
    "correctAnswerText": "Vertex",
    "explanation": "The correct answer is Vertex."
  },
  {
    "id": "mcq-050",
    "mcqNumber": 50,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Face",
    "subject": "Face",
    "topic": "Face",
    "question": "The most favourable fetal presentation for vaginal delivery is:",
    "options": [
      "Vertex",
      "Shoulder",
      "Transverse lie",
      "Brow"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Vertex",
    "explanation": "The correct answer is Vertex."
  },
  {
    "id": "mcq-051",
    "mcqNumber": 51,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Brow",
    "subject": "Brow",
    "topic": "Brow",
    "question": "The fetal head is at the level of the ischial spines when the station is:",
    "options": [
      "–2",
      "–1",
      "0",
      "+2"
    ],
    "correctAnswer": 2,
    "correctAnswerText": "0",
    "explanation": "The correct answer is 0."
  },
  {
    "id": "mcq-052",
    "mcqNumber": 52,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "+2",
    "subject": "+2",
    "topic": "+2",
    "question": "Station –1 indicates that the presenting part is:",
    "options": [
      "1 cm above the ischial spines",
      "1 cm below the ischial spines",
      "At the pelvic outlet",
      "At +2 station"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "1 cm above the ischial spines",
    "explanation": "The correct answer is 1 cm above the ischial spines."
  },
  {
    "id": "mcq-053",
    "mcqNumber": 53,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "At +2 station",
    "subject": "At +2 station",
    "topic": "At +2 station",
    "question": "The first stage of labour is divided into:",
    "options": [
      "Latent and active phases",
      "Early and late puerperium",
      "Upper and lower phases",
      "Maternal and fetal phases"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Latent and active phases",
    "explanation": "The correct answer is Latent and active phases."
  },
  {
    "id": "mcq-054",
    "mcqNumber": 54,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Maternal and fetal phases",
    "subject": "Maternal and fetal phases",
    "topic": "Maternal and fetal phases",
    "question": "The partograph is primarily used to monitor:",
    "options": [
      "Progress of labour",
      "Menstrual cycle",
      "Pregnancy test",
      "Lactation only"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Progress of labour",
    "explanation": "The correct answer is Progress of labour."
  },
  {
    "id": "mcq-055",
    "mcqNumber": 55,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Lactation only",
    "subject": "Lactation only",
    "topic": "Lactation only",
    "question": "One important parameter recorded on a partograph is:",
    "options": [
      "Cervical dilatation",
      "Hair growth",
      "Maternal height",
      "Eye colour"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Cervical dilatation",
    "explanation": "The correct answer is Cervical dilatation."
  },
  {
    "id": "mcq-056",
    "mcqNumber": 56,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Induction of Labour & Oxytocin",
    "subject": "Induction of Labour & Oxytocin",
    "topic": "Induction of Labour & Oxytocin",
    "question": "Induction of labour means:",
    "options": [
      "Artificial initiation of labour",
      "Natural onset of labour",
      "Prevention of labour",
      "Surgical removal of placenta"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Artificial initiation of labour",
    "explanation": "The correct answer is Artificial initiation of labour."
  },
  {
    "id": "mcq-057",
    "mcqNumber": 57,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Surgical removal of placenta",
    "subject": "Surgical removal of placenta",
    "topic": "Surgical removal of placenta",
    "question": "A commonly used drug for induction/augmentation of labour is:",
    "options": [
      "Oxytocin",
      "Insulin",
      "Atropine",
      "Furosemide"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Oxytocin",
    "explanation": "The correct answer is Oxytocin."
  },
  {
    "id": "mcq-058",
    "mcqNumber": 58,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Furosemide",
    "subject": "Furosemide",
    "topic": "Furosemide",
    "question": "A commonly used cervical-ripening drug is:",
    "options": [
      "Prostaglandin",
      "Insulin",
      "Magnesium",
      "Heparin"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Prostaglandin",
    "explanation": "The correct answer is Prostaglandin."
  },
  {
    "id": "mcq-059",
    "mcqNumber": 59,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Heparin",
    "subject": "Heparin",
    "topic": "Heparin",
    "question": "Artificial rupture of membranes is called:",
    "options": [
      "Amniotomy",
      "Episiotomy",
      "Amniocentesis",
      "Hysterectomy"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Amniotomy",
    "explanation": "The correct answer is Amniotomy."
  },
  {
    "id": "mcq-060",
    "mcqNumber": 60,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Hysterectomy",
    "subject": "Hysterectomy",
    "topic": "Hysterectomy",
    "question": "Before induction of labour, the nurse should assess:",
    "options": [
      "Maternal condition",
      "Fetal condition",
      "Cervical status",
      "All of the above"
    ],
    "correctAnswer": 3,
    "correctAnswerText": "All of the above",
    "explanation": "The correct answer is All of the above."
  },
  {
    "id": "mcq-061",
    "mcqNumber": 61,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "All of the above",
    "subject": "All of the above",
    "topic": "All of the above",
    "question": "The Bishop score assesses:",
    "options": [
      "Cervical favourability",
      "Fetal weight",
      "Maternal haemoglobin",
      "Placental maturity only"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Cervical favourability",
    "explanation": "The correct answer is Cervical favourability."
  },
  {
    "id": "mcq-062",
    "mcqNumber": 62,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Placental maturity only",
    "subject": "Placental maturity only",
    "topic": "Placental maturity only",
    "question": "Oxytocin primarily causes:",
    "options": [
      "Uterine contraction",
      "Cervical infection",
      "Fetal movement",
      "Milk production only"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Uterine contraction",
    "explanation": "The correct answer is Uterine contraction."
  },
  {
    "id": "mcq-063",
    "mcqNumber": 63,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Milk production only",
    "subject": "Milk production only",
    "topic": "Milk production only",
    "question": "Oxytocin is also important in:",
    "options": [
      "Milk ejection",
      "Ovulation",
      "Implantation",
      "Fertilization"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Milk ejection",
    "explanation": "The correct answer is Milk ejection."
  },
  {
    "id": "mcq-064",
    "mcqNumber": 64,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Fertilization",
    "subject": "Fertilization",
    "topic": "Fertilization",
    "question": "Excessive oxytocin infusion may cause:",
    "options": [
      "Uterine hyperstimulation",
      "Reduced uterine activity",
      "Anaemia",
      "Hypoglycaemia"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Uterine hyperstimulation",
    "explanation": "The correct answer is Uterine hyperstimulation."
  },
  {
    "id": "mcq-065",
    "mcqNumber": 65,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Hypoglycaemia",
    "subject": "Hypoglycaemia",
    "topic": "Hypoglycaemia",
    "question": "If excessive uterine contractions occur during oxytocin infusion, the priority is to:",
    "options": [
      "Increase oxytocin",
      "Stop the oxytocin infusion",
      "Give oral iron",
      "Encourage walking"
    ],
    "correctAnswer": 1,
    "correctAnswerText": "Stop the oxytocin infusion",
    "explanation": "The correct answer is Stop the oxytocin infusion."
  },
  {
    "id": "mcq-066",
    "mcqNumber": 66,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Preeclampsia & Eclampsia",
    "subject": "Preeclampsia & Eclampsia",
    "topic": "Preeclampsia & Eclampsia",
    "question": "Preeclampsia develops after:",
    "options": [
      "10 weeks",
      "12 weeks",
      "20 weeks",
      "Delivery only"
    ],
    "correctAnswer": 2,
    "correctAnswerText": "20 weeks",
    "explanation": "The correct answer is 20 weeks."
  },
  {
    "id": "mcq-067",
    "mcqNumber": 67,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Delivery only",
    "subject": "Delivery only",
    "topic": "Delivery only",
    "question": "A characteristic feature of preeclampsia is:",
    "options": [
      "Hypertension",
      "Hypoglycaemia",
      "Bradycardia",
      "Low temperature"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Hypertension",
    "explanation": "The correct answer is Hypertension."
  },
  {
    "id": "mcq-068",
    "mcqNumber": 68,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Low temperature",
    "subject": "Low temperature",
    "topic": "Low temperature",
    "question": "Severe preeclampsia may be associated with:",
    "options": [
      "Severe headache",
      "Visual disturbances",
      "Epigastric pain",
      "All of the above"
    ],
    "correctAnswer": 3,
    "correctAnswerText": "All of the above",
    "explanation": "The correct answer is All of the above."
  },
  {
    "id": "mcq-069",
    "mcqNumber": 69,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "All of the above",
    "subject": "All of the above",
    "topic": "All of the above",
    "question": "Eclampsia is characterized by:",
    "options": [
      "Convulsions in a woman with preeclampsia",
      "Anaemia only",
      "Hyperglycaemia only",
      "Labour pain only"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Convulsions in a woman with preeclampsia",
    "explanation": "The correct answer is Convulsions in a woman with preeclampsia."
  },
  {
    "id": "mcq-070",
    "mcqNumber": 70,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Labour pain only",
    "subject": "Labour pain only",
    "topic": "Labour pain only",
    "question": "The drug commonly used to prevent/treat eclamptic seizures is:",
    "options": [
      "Magnesium sulphate",
      "Oxytocin",
      "Insulin",
      "Iron"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Magnesium sulphate",
    "explanation": "The correct answer is Magnesium sulphate."
  },
  {
    "id": "mcq-071",
    "mcqNumber": 71,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Iron",
    "subject": "Iron",
    "topic": "Iron",
    "question": "Magnesium sulphate is primarily used in eclampsia to:",
    "options": [
      "Control/prevent convulsions",
      "Induce labour",
      "Reduce blood glucose",
      "Treat anaemia"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Control/prevent convulsions",
    "explanation": "The correct answer is Control/prevent convulsions."
  },
  {
    "id": "mcq-072",
    "mcqNumber": 72,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Treat anaemia",
    "subject": "Treat anaemia",
    "topic": "Treat anaemia",
    "question": "An important assessment during magnesium sulphate therapy is:",
    "options": [
      "Deep tendon reflexes",
      "Hair colour",
      "Weight of placenta",
      "Cervical length only"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Deep tendon reflexes",
    "explanation": "The correct answer is Deep tendon reflexes."
  },
  {
    "id": "mcq-073",
    "mcqNumber": 73,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Cervical length only",
    "subject": "Cervical length only",
    "topic": "Cervical length only",
    "question": "Respiratory depression may indicate:",
    "options": [
      "Magnesium sulphate toxicity",
      "Normal labour",
      "GDM",
      "Placenta previa"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Magnesium sulphate toxicity",
    "explanation": "The correct answer is Magnesium sulphate toxicity."
  },
  {
    "id": "mcq-074",
    "mcqNumber": 74,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Placenta previa",
    "subject": "Placenta previa",
    "topic": "Placenta previa",
    "question": "The antidote for magnesium sulphate toxicity is:",
    "options": [
      "Calcium gluconate",
      "Oxytocin",
      "Insulin",
      "Vitamin K"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Calcium gluconate",
    "explanation": "The correct answer is Calcium gluconate."
  },
  {
    "id": "mcq-075",
    "mcqNumber": 75,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Vitamin K",
    "subject": "Vitamin K",
    "topic": "Vitamin K",
    "question": "One serious maternal complication of eclampsia is:",
    "options": [
      "Cerebral haemorrhage",
      "Myopia",
      "Appendicitis",
      "Otitis"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Cerebral haemorrhage",
    "explanation": "The correct answer is Cerebral haemorrhage."
  },
  {
    "id": "mcq-076",
    "mcqNumber": 76,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "PPH & Obstetric Emergencies",
    "subject": "PPH & Obstetric Emergencies",
    "topic": "PPH & Obstetric Emergencies",
    "question": "PPH stands for:",
    "options": [
      "Postpartum Haemorrhage",
      "Pregnancy Pressure Haemorrhage",
      "Post-pregnancy Hypertension",
      "Placental Pressure Haemorrhage"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Postpartum Haemorrhage",
    "explanation": "The correct answer is Postpartum Haemorrhage."
  },
  {
    "id": "mcq-077",
    "mcqNumber": 77,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Placental Pressure Haemorrhage",
    "subject": "Placental Pressure Haemorrhage",
    "topic": "Placental Pressure Haemorrhage",
    "question": "The most common cause of primary PPH is:",
    "options": [
      "Uterine atony",
      "Anaemia",
      "Hyperemesis",
      "GDM"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Uterine atony",
    "explanation": "The correct answer is Uterine atony."
  },
  {
    "id": "mcq-078",
    "mcqNumber": 78,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "GDM",
    "subject": "GDM",
    "topic": "GDM",
    "question": "The four major causes of PPH are commonly remembered as:",
    "options": [
      "4 Ts",
      "4 Ps",
      "4 Cs",
      "4 As"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "4 Ts",
    "explanation": "The correct answer is 4 Ts."
  },
  {
    "id": "mcq-079",
    "mcqNumber": 79,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "4 As",
    "subject": "4 As",
    "topic": "4 As",
    "question": "In the 4 Ts of PPH, “Tone” refers to:",
    "options": [
      "Uterine atony",
      "Retained placenta",
      "Trauma",
      "Coagulopathy"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Uterine atony",
    "explanation": "The correct answer is Uterine atony."
  },
  {
    "id": "mcq-080",
    "mcqNumber": 80,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Coagulopathy",
    "subject": "Coagulopathy",
    "topic": "Coagulopathy",
    "question": "“Tissue” in PPH refers mainly to:",
    "options": [
      "Retained placental tissue",
      "Cervical tear",
      "Uterine contraction",
      "Anaemia"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Retained placental tissue",
    "explanation": "The correct answer is Retained placental tissue."
  },
  {
    "id": "mcq-081",
    "mcqNumber": 81,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Anaemia",
    "subject": "Anaemia",
    "topic": "Anaemia",
    "question": "“Trauma” in PPH may include:",
    "options": [
      "Genital tract laceration",
      "GDM",
      "Anaemia",
      "Hyperemesis"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Genital tract laceration",
    "explanation": "The correct answer is Genital tract laceration."
  },
  {
    "id": "mcq-082",
    "mcqNumber": 82,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Hyperemesis",
    "subject": "Hyperemesis",
    "topic": "Hyperemesis",
    "question": "Initial nursing management of atonic PPH includes:",
    "options": [
      "Uterine massage",
      "Giving food",
      "Encouraging sleep",
      "Delaying assessment"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Uterine massage",
    "explanation": "The correct answer is Uterine massage."
  },
  {
    "id": "mcq-083",
    "mcqNumber": 83,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Delaying assessment",
    "subject": "Delaying assessment",
    "topic": "Delaying assessment",
    "question": "A uterotonic commonly used to control uterine atony is:",
    "options": [
      "Oxytocin",
      "Insulin",
      "Diazepam",
      "Calcium"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Oxytocin",
    "explanation": "The correct answer is Oxytocin."
  },
  {
    "id": "mcq-084",
    "mcqNumber": 84,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Calcium",
    "subject": "Calcium",
    "topic": "Calcium",
    "question": "B-Lynch suture is used mainly to:",
    "options": [
      "Compress the uterus",
      "Suture the cervix",
      "Repair the vagina",
      "Close the bladder"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Compress the uterus",
    "explanation": "The correct answer is Compress the uterus."
  },
  {
    "id": "mcq-085",
    "mcqNumber": 85,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Close the bladder",
    "subject": "Close the bladder",
    "topic": "Close the bladder",
    "question": "A woman with PPH should be assessed frequently for:",
    "options": [
      "Vital signs and blood loss",
      "Hair loss",
      "Vision only",
      "Appetite only"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Vital signs and blood loss",
    "explanation": "The correct answer is Vital signs and blood loss."
  },
  {
    "id": "mcq-086",
    "mcqNumber": 86,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Placenta, Cord & Obstetric Bleeding",
    "subject": "Placenta, Cord & Obstetric Bleeding",
    "topic": "Placenta, Cord & Obstetric Bleeding",
    "question": "Placenta previa usually presents with:",
    "options": [
      "Painless vaginal bleeding",
      "Severe painful bleeding always",
      "Convulsions",
      "Fever only"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Painless vaginal bleeding",
    "explanation": "The correct answer is Painless vaginal bleeding."
  },
  {
    "id": "mcq-087",
    "mcqNumber": 87,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Fever only",
    "subject": "Fever only",
    "topic": "Fever only",
    "question": "Abruptio placentae is usually associated with:",
    "options": [
      "Painful vaginal bleeding",
      "Painless bleeding only",
      "No uterine tenderness",
      "Hypoglycaemia"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Painful vaginal bleeding",
    "explanation": "The correct answer is Painful vaginal bleeding."
  },
  {
    "id": "mcq-088",
    "mcqNumber": 88,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Hypoglycaemia",
    "subject": "Hypoglycaemia",
    "topic": "Hypoglycaemia",
    "question": "In suspected placenta previa, vaginal examination should be:",
    "options": [
      "Performed routinely",
      "Avoided until placenta location is known",
      "Performed repeatedly at home",
      "Done without precautions"
    ],
    "correctAnswer": 1,
    "correctAnswerText": "Avoided until placenta location is known",
    "explanation": "The correct answer is Avoided until placenta location is known."
  },
  {
    "id": "mcq-089",
    "mcqNumber": 89,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Done without precautions",
    "subject": "Done without precautions",
    "topic": "Done without precautions",
    "question": "Cord prolapse means:",
    "options": [
      "Umbilical cord descends below the presenting part",
      "Placenta separates early",
      "Cervix becomes closed",
      "Fetus becomes macrosomic"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Umbilical cord descends below the presenting part",
    "explanation": "The correct answer is Umbilical cord descends below the presenting part."
  },
  {
    "id": "mcq-090",
    "mcqNumber": 90,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Fetus becomes macrosomic",
    "subject": "Fetus becomes macrosomic",
    "topic": "Fetus becomes macrosomic",
    "question": "A priority in cord prolapse is to:",
    "options": [
      "Relieve pressure on the cord",
      "Encourage pushing",
      "Give oral iron",
      "Delay intervention"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Relieve pressure on the cord",
    "explanation": "The correct answer is Relieve pressure on the cord."
  },
  {
    "id": "mcq-091",
    "mcqNumber": 91,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Delay intervention",
    "subject": "Delay intervention",
    "topic": "Delay intervention",
    "question": "A major danger of cord prolapse is:",
    "options": [
      "Fetal hypoxia",
      "Maternal anaemia only",
      "GDM",
      "Puerperal psychosis"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Fetal hypoxia",
    "explanation": "The correct answer is Fetal hypoxia."
  },
  {
    "id": "mcq-092",
    "mcqNumber": 92,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Puerperal psychosis",
    "subject": "Puerperal psychosis",
    "topic": "Puerperal psychosis",
    "question": "Placental abruption means:",
    "options": [
      "Premature separation of normally implanted placenta",
      "Low implantation of placenta",
      "Failure of ovulation",
      "Retained placenta after abortion"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Premature separation of normally implanted placenta",
    "explanation": "The correct answer is Premature separation of normally implanted placenta."
  },
  {
    "id": "mcq-093",
    "mcqNumber": 93,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Retained placenta after abortion",
    "subject": "Retained placenta after abortion",
    "topic": "Retained placenta after abortion",
    "question": "Placenta previa means placenta is implanted:",
    "options": [
      "Near or over the internal cervical os",
      "In the ovary",
      "In the vagina",
      "In the fallopian tube"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Near or over the internal cervical os",
    "explanation": "The correct answer is Near or over the internal cervical os."
  },
  {
    "id": "mcq-094",
    "mcqNumber": 94,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Puerperium",
    "subject": "Puerperium",
    "topic": "Puerperium",
    "question": "Puerperium is the period following childbirth during which:",
    "options": [
      "The reproductive organs return toward the non-pregnant state",
      "Fertilization occurs",
      "Pregnancy begins",
      "Menopause starts"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "The reproductive organs return toward the non-pregnant state",
    "explanation": "The correct answer is The reproductive organs return toward the non-pregnant state."
  },
  {
    "id": "mcq-095",
    "mcqNumber": 95,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Menopause starts",
    "subject": "Menopause starts",
    "topic": "Menopause starts",
    "question": "Puerperium generally lasts approximately:",
    "options": [
      "1 week",
      "2 weeks",
      "6 weeks",
      "6 months"
    ],
    "correctAnswer": 2,
    "correctAnswerText": "6 weeks",
    "explanation": "The correct answer is 6 weeks."
  },
  {
    "id": "mcq-096",
    "mcqNumber": 96,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "6 months",
    "subject": "6 months",
    "topic": "6 months",
    "question": "The process by which the uterus returns to its pre-pregnant size is called:",
    "options": [
      "Involution",
      "Implantation",
      "Ovulation",
      "Fertilization"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Involution",
    "explanation": "The correct answer is Involution."
  },
  {
    "id": "mcq-097",
    "mcqNumber": 97,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Fertilization",
    "subject": "Fertilization",
    "topic": "Fertilization",
    "question": "Lochia refers to:",
    "options": [
      "Vaginal discharge after childbirth",
      "Breast milk",
      "Amniotic fluid",
      "Urine"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Vaginal discharge after childbirth",
    "explanation": "The correct answer is Vaginal discharge after childbirth."
  },
  {
    "id": "mcq-098",
    "mcqNumber": 98,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Urine",
    "subject": "Urine",
    "topic": "Urine",
    "question": "Lochia rubra is usually:",
    "options": [
      "Red",
      "White",
      "Yellow-green",
      "Colourless"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Red",
    "explanation": "The correct answer is Red."
  },
  {
    "id": "mcq-099",
    "mcqNumber": 99,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Colourless",
    "subject": "Colourless",
    "topic": "Colourless",
    "question": "Lochia serosa is usually:",
    "options": [
      "Pinkish/brownish",
      "Bright red only",
      "Green",
      "Black"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Pinkish/brownish",
    "explanation": "The correct answer is Pinkish/brownish."
  },
  {
    "id": "mcq-100",
    "mcqNumber": 100,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Black",
    "subject": "Black",
    "topic": "Black",
    "question": "Lochia alba is generally:",
    "options": [
      "Whitish/yellowish",
      "Bright red",
      "Blue",
      "Black"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Whitish/yellowish",
    "explanation": "The correct answer is Whitish/yellowish."
  },
  {
    "id": "mcq-101",
    "mcqNumber": 101,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Black",
    "subject": "Black",
    "topic": "Black",
    "question": "A normal postpartum uterus should:",
    "options": [
      "Gradually involute",
      "Remain enlarged permanently",
      "Increase in size",
      "Become absent"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Gradually involute",
    "explanation": "The correct answer is Gradually involute."
  },
  {
    "id": "mcq-102",
    "mcqNumber": 102,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Become absent",
    "subject": "Become absent",
    "topic": "Become absent",
    "question": "Breastfeeding promotes uterine contraction mainly through:",
    "options": [
      "Oxytocin",
      "Insulin",
      "FSH",
      "Thyroxine"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Oxytocin",
    "explanation": "The correct answer is Oxytocin."
  },
  {
    "id": "mcq-103",
    "mcqNumber": 103,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Puerperal Sepsis & Postnatal Care",
    "subject": "Puerperal Sepsis & Postnatal Care",
    "topic": "Puerperal Sepsis & Postnatal Care",
    "question": "Puerperal sepsis is:",
    "options": [
      "Infection of the genital tract following childbirth/abortion",
      "Anaemia during pregnancy",
      "Hypertension before pregnancy",
      "Diabetes in pregnancy"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Infection of the genital tract following childbirth/abortion",
    "explanation": "The correct answer is Infection of the genital tract following childbirth/abortion."
  },
  {
    "id": "mcq-104",
    "mcqNumber": 104,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Diabetes in pregnancy",
    "subject": "Diabetes in pregnancy",
    "topic": "Diabetes in pregnancy",
    "question": "A common sign of puerperal infection is:",
    "options": [
      "Fever",
      "Improved appetite",
      "Normal lochia only",
      "Increased height"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Fever",
    "explanation": "The correct answer is Fever."
  },
  {
    "id": "mcq-105",
    "mcqNumber": 105,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Increased height",
    "subject": "Increased height",
    "topic": "Increased height",
    "question": "Foul-smelling lochia may indicate:",
    "options": [
      "Puerperal infection",
      "Normal lactation",
      "GDM",
      "Ovulation"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Puerperal infection",
    "explanation": "The correct answer is Puerperal infection."
  },
  {
    "id": "mcq-106",
    "mcqNumber": 106,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Ovulation",
    "subject": "Ovulation",
    "topic": "Ovulation",
    "question": "An important method of preventing puerperal infection is:",
    "options": [
      "Strict aseptic technique",
      "Unnecessary vaginal examination",
      "Poor hand hygiene",
      "Reusing contaminated equipment"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Strict aseptic technique",
    "explanation": "The correct answer is Strict aseptic technique."
  },
  {
    "id": "mcq-107",
    "mcqNumber": 107,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Reusing contaminated equipment",
    "subject": "Reusing contaminated equipment",
    "topic": "Reusing contaminated equipment",
    "question": "Hand hygiene is important because it:",
    "options": [
      "Reduces transmission of infection",
      "Causes labour",
      "Increases blood pressure",
      "Prevents ovulation"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Reduces transmission of infection",
    "explanation": "The correct answer is Reduces transmission of infection."
  },
  {
    "id": "mcq-108",
    "mcqNumber": 108,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Prevents ovulation",
    "subject": "Prevents ovulation",
    "topic": "Prevents ovulation",
    "question": "During postnatal care, the nurse should assess:",
    "options": [
      "Uterine involution",
      "Lochia",
      "Perineum",
      "All of the above"
    ],
    "correctAnswer": 3,
    "correctAnswerText": "All of the above",
    "explanation": "The correct answer is All of the above."
  },
  {
    "id": "mcq-109",
    "mcqNumber": 109,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Preterm & Low Birth Weight Baby",
    "subject": "Preterm & Low Birth Weight Baby",
    "topic": "Preterm & Low Birth Weight Baby",
    "question": "A preterm baby is born before:",
    "options": [
      "28 completed weeks",
      "32 completed weeks",
      "37 completed weeks",
      "40 completed weeks"
    ],
    "correctAnswer": 2,
    "correctAnswerText": "37 completed weeks",
    "explanation": "The correct answer is 37 completed weeks."
  },
  {
    "id": "mcq-110",
    "mcqNumber": 110,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "40 completed weeks",
    "subject": "40 completed weeks",
    "topic": "40 completed weeks",
    "question": "Low birth weight means birth weight less than:",
    "options": [
      "1000 g",
      "1500 g",
      "2000 g",
      "2500 g"
    ],
    "correctAnswer": 3,
    "correctAnswerText": "2500 g",
    "explanation": "The correct answer is 2500 g."
  },
  {
    "id": "mcq-111",
    "mcqNumber": 111,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "2500 g",
    "subject": "2500 g",
    "topic": "2500 g",
    "question": "LBW is defined irrespective of:",
    "options": [
      "Gestational age",
      "Maternal age only",
      "Sex only",
      "Blood group"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Gestational age",
    "explanation": "The correct answer is Gestational age."
  },
  {
    "id": "mcq-112",
    "mcqNumber": 112,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Blood group",
    "subject": "Blood group",
    "topic": "Blood group",
    "question": "A common characteristic of a preterm baby is:",
    "options": [
      "Thin skin",
      "Excessive subcutaneous fat",
      "Mature lungs always",
      "Strong muscle tone"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Thin skin",
    "explanation": "The correct answer is Thin skin."
  },
  {
    "id": "mcq-113",
    "mcqNumber": 113,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Strong muscle tone",
    "subject": "Strong muscle tone",
    "topic": "Strong muscle tone",
    "question": "Preterm babies are particularly prone to:",
    "options": [
      "Hypothermia",
      "Hypertension",
      "Obesity immediately",
      "Hyperthermia always"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Hypothermia",
    "explanation": "The correct answer is Hypothermia."
  },
  {
    "id": "mcq-114",
    "mcqNumber": 114,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Hyperthermia always",
    "subject": "Hyperthermia always",
    "topic": "Hyperthermia always",
    "question": "A major complication of prematurity is:",
    "options": [
      "Respiratory distress syndrome",
      "Placenta previa",
      "Preeclampsia",
      "PPH in the baby"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Respiratory distress syndrome",
    "explanation": "The correct answer is Respiratory distress syndrome."
  },
  {
    "id": "mcq-115",
    "mcqNumber": 115,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "PPH in the baby",
    "subject": "PPH in the baby",
    "topic": "PPH in the baby",
    "question": "Another complication of prematurity is:",
    "options": [
      "Hypoglycaemia",
      "Maternal hypertension",
      "Uterine rupture",
      "Placental abruption"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Hypoglycaemia",
    "explanation": "The correct answer is Hypoglycaemia."
  },
  {
    "id": "mcq-116",
    "mcqNumber": 116,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Placental abruption",
    "subject": "Placental abruption",
    "topic": "Placental abruption",
    "question": "The best method for maintaining warmth in an appropriate stable newborn is:",
    "options": [
      "Skin-to-skin contact",
      "Cold bath",
      "Leaving the baby uncovered",
      "Cold room"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Skin-to-skin contact",
    "explanation": "The correct answer is Skin-to-skin contact."
  },
  {
    "id": "mcq-117",
    "mcqNumber": 117,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Cold room",
    "subject": "Cold room",
    "topic": "Cold room",
    "question": "KMC stands for:",
    "options": [
      "Kangaroo Mother Care",
      "Kangaroo Medical Consultation",
      "Kidney Monitoring Care",
      "Kangaroo Maternal Counselling"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Kangaroo Mother Care",
    "explanation": "The correct answer is Kangaroo Mother Care."
  },
  {
    "id": "mcq-118",
    "mcqNumber": 118,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Kangaroo Maternal Counselling",
    "subject": "Kangaroo Maternal Counselling",
    "topic": "Kangaroo Maternal Counselling",
    "question": "Kangaroo mother care mainly promotes:",
    "options": [
      "Warmth and breastfeeding",
      "Hypothermia",
      "Infection",
      "Separation from mother"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Warmth and breastfeeding",
    "explanation": "The correct answer is Warmth and breastfeeding."
  },
  {
    "id": "mcq-119",
    "mcqNumber": 119,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Separation from mother",
    "subject": "Separation from mother",
    "topic": "Separation from mother",
    "question": "A low birth weight baby in NICU requires close monitoring of:",
    "options": [
      "Temperature",
      "Blood glucose",
      "Respiration",
      "All of the above"
    ],
    "correctAnswer": 3,
    "correctAnswerText": "All of the above",
    "explanation": "The correct answer is All of the above."
  },
  {
    "id": "mcq-120",
    "mcqNumber": 120,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "All of the above",
    "subject": "All of the above",
    "topic": "All of the above",
    "question": "One important principle of LBW care is:",
    "options": [
      "Prevention of infection",
      "Unnecessary handling",
      "Delayed feeding",
      "Exposure to cold"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Prevention of infection",
    "explanation": "The correct answer is Prevention of infection."
  },
  {
    "id": "mcq-121",
    "mcqNumber": 121,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Neonatal Care & Asphyxia",
    "subject": "Neonatal Care & Asphyxia",
    "topic": "Neonatal Care & Asphyxia",
    "question": "Essential newborn care begins:",
    "options": [
      "Immediately after birth",
      "After 24 hours",
      "After one week",
      "After discharge"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Immediately after birth",
    "explanation": "The correct answer is Immediately after birth."
  },
  {
    "id": "mcq-122",
    "mcqNumber": 122,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "After discharge",
    "subject": "After discharge",
    "topic": "After discharge",
    "question": "Apgar score is assessed at:",
    "options": [
      "1 and 5 minutes",
      "10 and 20 minutes only",
      "1 hour only",
      "24 hours"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "1 and 5 minutes",
    "explanation": "The correct answer is 1 and 5 minutes."
  },
  {
    "id": "mcq-123",
    "mcqNumber": 123,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "24 hours",
    "subject": "24 hours",
    "topic": "24 hours",
    "question": "Apgar score includes:",
    "options": [
      "Heart rate",
      "Respiratory effort",
      "Muscle tone",
      "All of the above"
    ],
    "correctAnswer": 3,
    "correctAnswerText": "All of the above",
    "explanation": "The correct answer is All of the above."
  },
  {
    "id": "mcq-124",
    "mcqNumber": 124,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "All of the above",
    "subject": "All of the above",
    "topic": "All of the above",
    "question": "The maximum Apgar score is:",
    "options": [
      "5",
      "7",
      "10",
      "15"
    ],
    "correctAnswer": 2,
    "correctAnswerText": "10",
    "explanation": "The correct answer is 10."
  },
  {
    "id": "mcq-125",
    "mcqNumber": 125,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "15",
    "subject": "15",
    "topic": "15",
    "question": "A newborn with poor respiratory effort requires:",
    "options": [
      "Immediate assessment and appropriate resuscitation",
      "Delayed observation",
      "Oral feeding immediately",
      "Bathing first"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Immediate assessment and appropriate resuscitation",
    "explanation": "The correct answer is Immediate assessment and appropriate resuscitation."
  },
  {
    "id": "mcq-126",
    "mcqNumber": 126,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Bathing first",
    "subject": "Bathing first",
    "topic": "Bathing first",
    "question": "Neonatal asphyxia is mainly associated with:",
    "options": [
      "Failure to establish effective breathing at birth",
      "Maternal anaemia only",
      "High birth weight only",
      "Normal breathing"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Failure to establish effective breathing at birth",
    "explanation": "The correct answer is Failure to establish effective breathing at birth."
  },
  {
    "id": "mcq-127",
    "mcqNumber": 127,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Normal breathing",
    "subject": "Normal breathing",
    "topic": "Normal breathing",
    "question": "The first priority in a non-breathing newborn is:",
    "options": [
      "Establish effective ventilation",
      "Give oral fluids",
      "Bathe the baby",
      "Start breastfeeding immediately"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Establish effective ventilation",
    "explanation": "The correct answer is Establish effective ventilation."
  },
  {
    "id": "mcq-128",
    "mcqNumber": 128,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Start breastfeeding immediately",
    "subject": "Start breastfeeding immediately",
    "topic": "Start breastfeeding immediately",
    "question": "A newborn's respiratory rate is normally approximately:",
    "options": [
      "10–20/min",
      "20–30/min",
      "30–60/min",
      "80–100/min"
    ],
    "correctAnswer": 2,
    "correctAnswerText": "30–60/min",
    "explanation": "The correct answer is 30–60/min."
  },
  {
    "id": "mcq-129",
    "mcqNumber": 129,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "80–100/min",
    "subject": "80–100/min",
    "topic": "80–100/min",
    "question": "Grunting in a newborn may indicate:",
    "options": [
      "Respiratory distress",
      "Normal digestion",
      "Hyperglycaemia",
      "Good oxygenation"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Respiratory distress",
    "explanation": "The correct answer is Respiratory distress."
  },
  {
    "id": "mcq-130",
    "mcqNumber": 130,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Good oxygenation",
    "subject": "Good oxygenation",
    "topic": "Good oxygenation",
    "question": "Chest retractions in a newborn suggest:",
    "options": [
      "Respiratory difficulty",
      "Normal respiration",
      "Normal feeding",
      "Jaundice"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Respiratory difficulty",
    "explanation": "The correct answer is Respiratory difficulty."
  },
  {
    "id": "mcq-131",
    "mcqNumber": 131,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Neonatal Jaundice & Phototherapy",
    "subject": "Neonatal Jaundice & Phototherapy",
    "topic": "Neonatal Jaundice & Phototherapy",
    "question": "Physiological jaundice usually appears:",
    "options": [
      "Within the first 24 hours",
      "After the first 24 hours",
      "Before birth always",
      "At 1 year"
    ],
    "correctAnswer": 1,
    "correctAnswerText": "After the first 24 hours",
    "explanation": "The correct answer is After the first 24 hours."
  },
  {
    "id": "mcq-132",
    "mcqNumber": 132,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "At 1 year",
    "subject": "At 1 year",
    "topic": "At 1 year",
    "question": "Jaundice appearing within the first 24 hours is considered:",
    "options": [
      "Physiological always",
      "Pathological until evaluated",
      "Normal in all babies",
      "A sign of good health"
    ],
    "correctAnswer": 1,
    "correctAnswerText": "Pathological until evaluated",
    "explanation": "The correct answer is Pathological until evaluated."
  },
  {
    "id": "mcq-133",
    "mcqNumber": 133,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "A sign of good health",
    "subject": "A sign of good health",
    "topic": "A sign of good health",
    "question": "Physiological jaundice is mainly due to:",
    "options": [
      "Increased bilirubin production and immature bilirubin metabolism",
      "Excess insulin",
      "Maternal hypertension",
      "Placenta previa"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Increased bilirubin production and immature bilirubin metabolism",
    "explanation": "The correct answer is Increased bilirubin production and immature bilirubin metabolism."
  },
  {
    "id": "mcq-134",
    "mcqNumber": 134,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Placenta previa",
    "subject": "Placenta previa",
    "topic": "Placenta previa",
    "question": "Phototherapy is used to reduce:",
    "options": [
      "Serum bilirubin",
      "Blood pressure",
      "Blood glucose",
      "Maternal temperature"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Serum bilirubin",
    "explanation": "The correct answer is Serum bilirubin."
  },
  {
    "id": "mcq-135",
    "mcqNumber": 135,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Maternal temperature",
    "subject": "Maternal temperature",
    "topic": "Maternal temperature",
    "question": "During phototherapy, the baby's eyes should be:",
    "options": [
      "Protected",
      "Left uncovered",
      "Washed continuously",
      "Covered with cotton inside the mouth"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Protected",
    "explanation": "The correct answer is Protected."
  },
  {
    "id": "mcq-136",
    "mcqNumber": 136,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Covered with cotton inside the mouth",
    "subject": "Covered with cotton inside the mouth",
    "topic": "Covered with cotton inside the mouth",
    "question": "During phototherapy, adequate feeding is important to:",
    "options": [
      "Promote hydration and bilirubin excretion",
      "Increase bilirubin",
      "Cause dehydration",
      "Stop urine production"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Promote hydration and bilirubin excretion",
    "explanation": "The correct answer is Promote hydration and bilirubin excretion."
  },
  {
    "id": "mcq-137",
    "mcqNumber": 137,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Stop urine production",
    "subject": "Stop urine production",
    "topic": "Stop urine production",
    "question": "Severe untreated neonatal hyperbilirubinaemia may cause:",
    "options": [
      "Kernicterus",
      "PPH",
      "Eclampsia",
      "Placenta previa"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Kernicterus",
    "explanation": "The correct answer is Kernicterus."
  },
  {
    "id": "mcq-138",
    "mcqNumber": 138,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Lactation & Breastfeeding",
    "subject": "Lactation & Breastfeeding",
    "topic": "Lactation & Breastfeeding",
    "question": "The hormone mainly responsible for milk production is:",
    "options": [
      "Prolactin",
      "Oxytocin",
      "FSH",
      "hCG"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Prolactin",
    "explanation": "The correct answer is Prolactin."
  },
  {
    "id": "mcq-139",
    "mcqNumber": 139,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "hCG",
    "subject": "hCG",
    "topic": "hCG",
    "question": "The hormone mainly responsible for milk ejection is:",
    "options": [
      "Oxytocin",
      "Prolactin",
      "Estrogen",
      "Progesterone"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Oxytocin",
    "explanation": "The correct answer is Oxytocin."
  },
  {
    "id": "mcq-140",
    "mcqNumber": 140,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Progesterone",
    "subject": "Progesterone",
    "topic": "Progesterone",
    "question": "Colostrum is:",
    "options": [
      "The first breast secretion after childbirth",
      "Mature breast milk after one year",
      "Artificial milk",
      "Amniotic fluid"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "The first breast secretion after childbirth",
    "explanation": "The correct answer is The first breast secretion after childbirth."
  },
  {
    "id": "mcq-141",
    "mcqNumber": 141,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Amniotic fluid",
    "subject": "Amniotic fluid",
    "topic": "Amniotic fluid",
    "question": "Colostrum is particularly rich in:",
    "options": [
      "Immunoglobulins",
      "Alcohol",
      "Sodium chloride only",
      "Glucose only"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Immunoglobulins",
    "explanation": "The correct answer is Immunoglobulins."
  },
  {
    "id": "mcq-142",
    "mcqNumber": 142,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Glucose only",
    "subject": "Glucose only",
    "topic": "Glucose only",
    "question": "Exclusive breastfeeding is generally recommended for the first:",
    "options": [
      "1 month",
      "3 months",
      "6 months",
      "12 months"
    ],
    "correctAnswer": 2,
    "correctAnswerText": "6 months",
    "explanation": "The correct answer is 6 months."
  },
  {
    "id": "mcq-143",
    "mcqNumber": 143,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "12 months",
    "subject": "12 months",
    "topic": "12 months",
    "question": "Frequent suckling helps to:",
    "options": [
      "Maintain milk production",
      "Stop lactation",
      "Reduce prolactin completely",
      "Prevent milk ejection"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Maintain milk production",
    "explanation": "The correct answer is Maintain milk production."
  },
  {
    "id": "mcq-144",
    "mcqNumber": 144,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Prevent milk ejection",
    "subject": "Prevent milk ejection",
    "topic": "Prevent milk ejection",
    "question": "The let-down reflex is primarily mediated by:",
    "options": [
      "Oxytocin",
      "FSH",
      "hCG",
      "Estrogen"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Oxytocin",
    "explanation": "The correct answer is Oxytocin."
  },
  {
    "id": "mcq-145",
    "mcqNumber": 145,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Family Planning, Contraception & ART",
    "subject": "Family Planning, Contraception & ART",
    "topic": "Family Planning, Contraception & ART",
    "question": "Family planning mainly helps couples to:",
    "options": [
      "Plan the number and spacing of children",
      "Prevent all pregnancies permanently",
      "Treat all infertility",
      "Treat anaemia"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Plan the number and spacing of children",
    "explanation": "The correct answer is Plan the number and spacing of children."
  },
  {
    "id": "mcq-146",
    "mcqNumber": 146,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Treat anaemia",
    "subject": "Treat anaemia",
    "topic": "Treat anaemia",
    "question": "IUCD stands for:",
    "options": [
      "Intrauterine Contraceptive Device",
      "Internal Uterine Clinical Drug",
      "Intrauterine Clinical Diagnosis",
      "Internal Uterine Contraceptive Drug"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Intrauterine Contraceptive Device",
    "explanation": "The correct answer is Intrauterine Contraceptive Device."
  },
  {
    "id": "mcq-147",
    "mcqNumber": 147,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Internal Uterine Contraceptive Drug",
    "subject": "Internal Uterine Contraceptive Drug",
    "topic": "Internal Uterine Contraceptive Drug",
    "question": "Which is a permanent method of contraception for females?",
    "options": [
      "Tubal ligation",
      "Condom",
      "IUCD",
      "Oral contraceptive pill"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Tubal ligation",
    "explanation": "The correct answer is Tubal ligation."
  },
  {
    "id": "mcq-148",
    "mcqNumber": 148,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Oral contraceptive pill",
    "subject": "Oral contraceptive pill",
    "topic": "Oral contraceptive pill",
    "question": "Which is a permanent method of contraception for males?",
    "options": [
      "Vasectomy",
      "Condom",
      "IUCD",
      "Oral pill"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Vasectomy",
    "explanation": "The correct answer is Vasectomy."
  },
  {
    "id": "mcq-149",
    "mcqNumber": 149,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Oral pill",
    "subject": "Oral pill",
    "topic": "Oral pill",
    "question": "IVF stands for:",
    "options": [
      "In Vitro Fertilization",
      "Internal Vaginal Fertilization",
      "In Vivo Fetalization",
      "Internal Vital Fertilization"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "In Vitro Fertilization",
    "explanation": "The correct answer is In Vitro Fertilization."
  },
  {
    "id": "mcq-150",
    "mcqNumber": 150,
    "marks": "mcq",
    "status": "published",
    "priority": "important",
    "type": "mcq",
    "category": "Internal Vital Fertilization",
    "subject": "Internal Vital Fertilization",
    "topic": "Internal Vital Fertilization",
    "question": "In IVF, fertilization takes place:",
    "options": [
      "Outside the body in a laboratory",
      "Inside the uterus only",
      "Inside the vagina",
      "Inside the cervix"
    ],
    "correctAnswer": 0,
    "correctAnswerText": "Outside the body in a laboratory",
    "explanation": "The correct answer is Outside the body in a laboratory."
  }
];
if (typeof window !== 'undefined') window.MCQ_QUESTIONS = MCQ_QUESTIONS;
if (typeof module !== 'undefined') module.exports = { MCQ_QUESTIONS };

